import {
  Pharmacy,
  Medicine,
  Doctor,
  Category,
  Testimonial,
  FAQ,
  Order,
  Appointment,
  MedicinePrice,
  MedicalRecord,
} from "@/types";
import generatedData from "./generated-data.json";

export const pharmacies: Pharmacy[] = (generatedData.generatedPharmacies as any[]).map((p: any) => ({
  ...p,
  description: `${p.name} — ${p.city} shahridagi ishonchli dorixona. ${p.address}`,
  logo: `/images/pharmacy-${(parseInt(p.id.replace('ph-', '')) % 12) + 1}.svg`,
  coverImage: `/images/pharmacy-cover-${(parseInt(p.id.replace('ph-', '')) % 4) + 1}.svg`,
  email: `info@pharmacy${parseInt(p.id.replace('ph-', ''))}.uz`,
  zipCode: "100000",
  workingHours: {
    monday: { open: p.is24hours ? "00:00" : "08:00", close: p.is24hours ? "23:59" : "22:00", isOpen: true },
    tuesday: { open: p.is24hours ? "00:00" : "08:00", close: p.is24hours ? "23:59" : "22:00", isOpen: true },
    wednesday: { open: p.is24hours ? "00:00" : "08:00", close: p.is24hours ? "23:59" : "22:00", isOpen: true },
    thursday: { open: p.is24hours ? "00:00" : "08:00", close: p.is24hours ? "23:59" : "22:00", isOpen: true },
    friday: { open: p.is24hours ? "00:00" : "08:00", close: p.is24hours ? "23:59" : "22:00", isOpen: true },
    saturday: { open: p.is24hours ? "00:00" : "09:00", close: p.is24hours ? "23:59" : "20:00", isOpen: true },
    sunday: { open: p.is24hours ? "00:00" : "09:00", close: p.is24hours ? "23:59" : "18:00", isOpen: p.is24hours },
  },
  availableMedicines: [],
  createdAt: "2024-01-01",
  updatedAt: "2024-11-01",
}));

export const medicines: Medicine[] = (generatedData.generatedMedicines as any[]).map((m: any) => ({
  ...m,
  alternatives: [],
}));

export const medicinePrices: Record<string, MedicinePrice[]> = generatedData.generatedMedicinePrices as any;

export const doctors: Doctor[] = [
  {
    id: "doc-1",
    name: "Dr. Akbar Karimov",
    slug: "dr-akbar-karimov",
    photo: "/images/doctor-1.svg",
    specialty: "Terapevt",
    experience: 15,
    education: "Toshkent Tibbiyot Akademiyasi",
    languages: ["O'zbek", "Rus", "Ingliz"],
    rating: 4.9,
    reviewCount: 342,
    consultationFee: 80000,
    isAvailableToday: true,
    availableForVideo: true,
    availableForChat: true,
    availableForInPerson: true,
    bio: "15 yillik tajribaga ega terapevt. Bemorlarga individual yondashish va profilaktik tibbiyotga ixtisoslashgan.",
    qualifications: ["Terapiya - oliy toifa", "Tibbiyot fanlari nomzodi"],
    awards: ["Yilning eng yaxshi shifokori 2023"],
    availableSlots: [
      { date: "2024-11-15", startTime: "09:00", endTime: "09:30", isBooked: false, type: "video" },
      { date: "2024-11-15", startTime: "10:00", endTime: "10:30", isBooked: false, type: "video" },
      { date: "2024-11-15", startTime: "11:00", endTime: "11:30", isBooked: true, type: "chat" },
      { date: "2024-11-15", startTime: "14:00", endTime: "14:30", isBooked: false, type: "in-person" },
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-11-01",
  },
  {
    id: "doc-2",
    name: "Dr. Lola Rahmonova",
    slug: "dr-lola-rahmonova",
    photo: "/images/doctor-2.svg",
    specialty: "Kardiolog",
    experience: 18,
    education: "Samarqand Tibbiyot Instituti",
    languages: ["O'zbek", "Rus"],
    rating: 4.8,
    reviewCount: 521,
    consultationFee: 120000,
    isAvailableToday: true,
    availableForVideo: true,
    availableForChat: false,
    availableForInPerson: true,
    bio: "Yurak-qon tomir kasalliklarini tashxislash va davolash bo'yicha yetakchi kardiolog.",
    qualifications: ["Kardiologiya - oliy toifa", "Yurak ritmi buzilishlari bo'yicha mutaxassis"],
    awards: ["O'zbekiston sog'liqni saqlash a'lochisi"],
    availableSlots: [
      { date: "2024-11-15", startTime: "09:30", endTime: "10:00", isBooked: false, type: "video" },
      { date: "2024-11-15", startTime: "11:00", endTime: "11:30", isBooked: false, type: "video" },
      { date: "2024-11-15", startTime: "15:00", endTime: "15:30", isBooked: false, type: "in-person" },
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-11-01",
  },
  {
    id: "doc-3",
    name: "Dr. Jasur Tursunov",
    slug: "dr-jasur-tursunov",
    photo: "/images/doctor-3.svg",
    specialty: "Pediatr",
    experience: 12,
    education: "ToshkETI (Toshkent Pediatriya Tibbiyot Instituti)",
    languages: ["O'zbek", "Rus", "Ingliz"],
    rating: 4.9,
    reviewCount: 289,
    consultationFee: 70000,
    isAvailableToday: false,
    availableForVideo: true,
    availableForChat: true,
    availableForInPerson: true,
    bio: "Bolalar salomatligi bo'yicha tajribali pediatr. Go'daklikdan o'smirlik davrigacha bo'lgan bolalarga xizmat ko'rsatadi.",
    qualifications: ["Pediatriya - oliy toifa", "Bolalar allergologiyasi"],
    awards: ["Eng yaxshi pediatr 2024"],
    availableSlots: [
      { date: "2024-11-16", startTime: "09:00", endTime: "09:30", isBooked: false, type: "video" },
      { date: "2024-11-16", startTime: "10:00", endTime: "10:30", isBooked: false, type: "chat" },
      { date: "2024-11-16", startTime: "14:00", endTime: "14:30", isBooked: false, type: "in-person" },
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-11-01",
  },
  {
    id: "doc-4",
    name: "Dr. Nigora Azizova",
    slug: "dr-nigora-azizova",
    photo: "/images/doctor-4.svg",
    specialty: "Dermatolog",
    experience: 14,
    education: "Toshkent Tibbiyot Akademiyasi",
    languages: ["O'zbek", "Rus", "Ingliz"],
    rating: 4.7,
    reviewCount: 412,
    consultationFee: 90000,
    isAvailableToday: true,
    availableForVideo: true,
    availableForChat: true,
    availableForInPerson: true,
    bio: "Teri, soch va tirnoq kasalliklarini eng zamonaviy usullar bilan davolash bo'yicha mutaxassis.",
    qualifications: ["Dermatologiya - oliy toifa", "Kosmetologiya"],
    awards: ["Dermatologiya sohasidagi yutuqlar uchun 2023"],
    availableSlots: [
      { date: "2024-11-15", startTime: "10:00", endTime: "10:30", isBooked: false, type: "video" },
      { date: "2024-11-15", startTime: "13:00", endTime: "13:30", isBooked: false, type: "chat" },
      { date: "2024-11-15", startTime: "16:00", endTime: "16:30", isBooked: false, type: "in-person" },
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-11-01",
  },
  {
    id: "doc-5",
    name: "Dr. Bobur Hamidov",
    slug: "dr-bobur-hamidov",
    photo: "/images/doctor-5.svg",
    specialty: "Nevrolog",
    experience: 16,
    education: "Samarqand Tibbiyot Universiteti",
    languages: ["O'zbek", "Rus", "Ingliz"],
    rating: 4.8,
    reviewCount: 367,
    consultationFee: 100000,
    isAvailableToday: true,
    availableForVideo: true,
    availableForChat: false,
    availableForInPerson: true,
    bio: "Asab tizimi kasalliklari, migren, epilepsiya va neyrodegenerativ kasalliklarni davolash bo'yicha mutaxassis.",
    qualifications: ["Nevrologiya - oliy toifa", "Neyrofiziologiya"],
    awards: ["Neyrologiya sohasidagi tadqiqotlar uchun 2024"],
    availableSlots: [
      { date: "2024-11-15", startTime: "09:00", endTime: "09:30", isBooked: false, type: "video" },
      { date: "2024-11-15", startTime: "11:30", endTime: "12:00", isBooked: false, type: "in-person" },
      { date: "2024-11-15", startTime: "14:30", endTime: "15:00", isBooked: true, type: "in-person" },
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-11-01",
  },
  {
    id: "doc-6",
    name: "Dr. Gulnora Salimova",
    slug: "dr-gulnora-salimova",
    photo: "/images/doctor-6.svg",
    specialty: "Ortoped-Travmatolog",
    experience: 22,
    education: "Toshkent Tibbiyot Akademiyasi",
    languages: ["O'zbek", "Rus"],
    rating: 4.9,
    reviewCount: 634,
    consultationFee: 150000,
    isAvailableToday: false,
    availableForVideo: true,
    availableForChat: false,
    availableForInPerson: true,
    bio: "Sport tibbiyoti, bo'g'im protezlash va minimal invaziv umurtqa pog'onasi jarrohlik amaliyotlari bo'yicha tanilgan ortoped.",
    qualifications: ["Ortopediya - oliy toifa", "Sport tibbiyoti"],
    awards: ["Eng yaxshi jarroh 2023", "Bemor xavfsizligi mukofoti 2024"],
    availableSlots: [
      { date: "2024-11-18", startTime: "09:00", endTime: "09:30", isBooked: false, type: "video" },
      { date: "2024-11-18", startTime: "10:00", endTime: "10:30", isBooked: false, type: "in-person" },
      { date: "2024-11-18", startTime: "15:00", endTime: "15:30", isBooked: false, type: "in-person" },
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-11-01",
  },
];

export const categories: Category[] = [
  { id: "cat-1", name: "Og'riq qoldiruvchi", slug: "ogriq-qoldiruvchi", description: "Og'riq va isitmani tushirish uchun dorilar", image: "/images/medicines/paracetamol.jpg", icon: "Activity", medicineCount: medicines.filter(m => m.category === "Og'riq qoldiruvchi").length },
  { id: "cat-2", name: "Antibiotiklar", slug: "antibiotiklar", description: "Bakterial infeksiyalarni davolash uchun", image: "/images/medicines/capsule.jpg", icon: "Shield", medicineCount: medicines.filter(m => m.category === "Antibiotiklar").length },
  { id: "cat-3", name: "Yurak-qon tomir", slug: "yurak-qon-tomir", description: "Yurak va qon bosimi dorilari", image: "/images/medicines/spray.jpg", icon: "Heart", medicineCount: medicines.filter(m => m.category === "Yurak-qon tomir").length },
  { id: "cat-4", name: "Qandli diabet", slug: "qandli-diabet", description: "Qandli diabetni boshqarish uchun", image: "/images/medicines/injection.jpg", icon: "Droplet", medicineCount: medicines.filter(m => m.category === "Qandli diabet").length },
  { id: "cat-5", name: "Allergiyaga qarshi", slug: "allergiyaga-qarshi", description: "Antigistamin va allergiyaga qarshi", image: "/images/medicines/syrup.jpg", icon: "Wind", medicineCount: medicines.filter(m => m.category === "Allergiyaga qarshi").length },
  { id: "cat-6", name: "Ovqat hazm qilish", slug: "ovqat-hazm-qilish", description: "Ovqat hazm qilish va oshqozon dorilari", image: "/images/medicines/capsule.jpg", icon: "Stethoscope", medicineCount: medicines.filter(m => m.category === "Ovqat hazm qilish").length },
  { id: "cat-7", name: "Vitaminlar", slug: "vitaminlar", description: "Vitamin va biologik faol qo'shimchalar", image: "/images/medicines/paracetamol.jpg", icon: "Apple", medicineCount: medicines.filter(m => m.category === "Vitaminlar").length },
  { id: "cat-8", name: "Nafas olish", slug: "nafas-olish", description: "Nafas olish va astma dorilari", image: "/images/medicines/inhaler.jpg", icon: "Wind", medicineCount: medicines.filter(m => m.category === "Nafas olish").length },
  { id: "cat-9", name: "Gormonlar", slug: "gormonlar", description: "Gormonal preparatlar", image: "/images/medicines/injection.jpg", icon: "Activity", medicineCount: medicines.filter(m => m.category === "Gormonlar").length },
  { id: "cat-10", name: "Asab tizimi", slug: "asab-tizimi", description: "Asab tizimi uchun dorilar", image: "/images/medicines/capsule.jpg", icon: "Brain", medicineCount: medicines.filter(m => m.category === "Asab tizimi").length },
  { id: "cat-11", name: "Teri kasalliklari", slug: "teri-kasalliklari", description: "Terini parvarish qilish va davolash", image: "/images/medicines/gel.jpg", icon: "Wind", medicineCount: medicines.filter(m => m.category === "Teri kasalliklari").length },
  { id: "cat-12", name: "Immunitet", slug: "immunitet", description: "Immunitetni mustahkamlash", image: "/images/medicines/paracetamol.jpg", icon: "Shield", medicineCount: medicines.filter(m => m.category === "Immunitet").length },
  { id: "cat-13", name: "Ko'z dorilari", slug: "koz-dorilari", description: "Ko'z kasalliklari uchun", image: "/images/medicines/spray.jpg", icon: "Eye", medicineCount: medicines.filter(m => m.category === "Ko'z dorilari").length },
  { id: "cat-14", name: "Nafas yo'llari", slug: "nafas-yollari", description: "Nafas yo'llari kasalliklari", image: "/images/medicines/inhaler.jpg", icon: "Wind", medicineCount: medicines.filter(m => m.category === "Nafas yo'llari").length },
  { id: "cat-15", name: "Otolaringologiya", slug: "otolaringologiya", description: "Quloq, burun, tomoq kasalliklari", image: "/images/medicines/spray.jpg", icon: "Ear", medicineCount: medicines.filter(m => m.category === "Otolaringologiya").length },
  { id: "cat-16", name: "Bolalar", slug: "bolalar", description: "Bolalar uchun dori vositalari", image: "/images/medicines/syrup.jpg", icon: "Baby", medicineCount: medicines.filter(m => m.category === "Bolalar").length },
  { id: "cat-17", name: "Onkologiya", slug: "onkologiya", description: "Onkologiya preparatlari", image: "/images/medicines/injection.jpg", icon: "FlaskConical", medicineCount: medicines.filter(m => m.category === "Onkologiya").length },
  { id: "cat-18", name: "Ortopediya", slug: "ortopediya", description: "Bo'g'im va suyak kasalliklari", image: "/images/medicines/gel.jpg", icon: "Bone", medicineCount: medicines.filter(m => m.category === "Ortopediya").length },
  { id: "cat-19", name: "Ginekologiya", slug: "ginekologiya", description: "Ginekologiya preparatlari", image: "/images/medicines/suppository.jpg", icon: "Heart", medicineCount: medicines.filter(m => m.category === "Ginekologiya").length },
  { id: "cat-20", name: "Stomatologiya", slug: "stomatologiya", description: "Tish kasalliklari uchun", image: "/images/medicines/gel.jpg", icon: "Smile", medicineCount: medicines.filter(m => m.category === "Stomatologiya").length },
  { id: "cat-21", name: "Urologiya", slug: "urologiya", description: "Urologiya preparatlari", image: "/images/medicines/capsule.jpg", icon: "Droplet", medicineCount: medicines.filter(m => m.category === "Urologiya").length },
  { id: "cat-22", name: "Qon topish", slug: "qon-topish", description: "Qon topish kasalliklari uchun", image: "/images/medicines/injection.jpg", icon: "Droplet", medicineCount: medicines.filter(m => m.category === "Qon topish").length },
  { id: "cat-23", name: "Revmatologiya", slug: "revmatologiya", description: "Revmatologiya preparatlari", image: "/images/medicines/paracetamol.jpg", icon: "Bone", medicineCount: medicines.filter(m => m.category === "Revmatologiya").length },
  { id: "cat-24", name: "Endokrinologiya", slug: "endokrinologiya", description: "Endokrin tizim kasalliklari uchun", image: "/images/medicines/injection.jpg", icon: "Activity", medicineCount: medicines.filter(m => m.category === "Endokrinologiya").length },
  { id: "cat-25", name: "Gastroenterologiya", slug: "gastroenterologiya", description: "Ovqat hazm tizimi kasalliklari uchun", image: "/images/medicines/capsule.jpg", icon: "Stethoscope", medicineCount: medicines.filter(m => m.category === "Gastroenterologiya").length },
  { id: "cat-26", name: "Nevrologiya", slug: "nevrologiya", description: "Nevrologiya preparatlari", image: "/images/medicines/capsule.jpg", icon: "Brain", medicineCount: medicines.filter(m => m.category === "Nevrologiya").length },
  { id: "cat-27", name: "Psixiatriya", slug: "psixiatriya", description: "Psixiatriya preparatlari", image: "/images/medicines/paracetamol.jpg", icon: "Brain", medicineCount: medicines.filter(m => m.category === "Psixiatriya").length },
  { id: "cat-28", name: "Allergologiya", slug: "allergologiya", description: "Allergologiya mutaxassisligi dorilari", image: "/images/medicines/spray.jpg", icon: "Wind", medicineCount: medicines.filter(m => m.category === "Allergologiya").length },
  { id: "cat-29", name: "Immunologiya", slug: "immunologiya", description: "Immunologiya preparatlari", image: "/images/medicines/injection.jpg", icon: "Shield", medicineCount: medicines.filter(m => m.category === "Immunologiya").length },
  { id: "cat-30", name: "Onkologiya-kimyo", slug: "onkologiya-kimyo", description: "Kimyo terapiya preparatlari", image: "/images/medicines/injection.jpg", icon: "FlaskConical", medicineCount: medicines.filter(m => m.category === "Onkologiya-kimyo").length },
  { id: "cat-31", name: "Sport tibbiyoti", slug: "sport-tibbiyoti", description: "Sport tibbiyoti vositalari", image: "/images/medicines/paracetamol.jpg", icon: "Dumbbell", medicineCount: medicines.filter(m => m.category === "Sport tibbiyoti").length },
  { id: "cat-32", name: "Kosmetologiya", slug: "kosmetologiya", description: "Kosmetologiya vositalari", image: "/images/medicines/gel.jpg", icon: "Sparkles", medicineCount: medicines.filter(m => m.category === "Kosmetologiya").length },
  { id: "cat-33", name: "Gigiena", slug: "gigiena", description: "Shaxsiy gigiena vositalari", image: "/images/medicines/gel.jpg", icon: "Droplets", medicineCount: medicines.filter(m => m.category === "Gigiena").length },
  { id: "cat-34", name: "Tibbiy buyumlar", slug: "tibbiy-buyumlar", description: "Tibbiy buyumlar va asboblar", image: "/images/medicines/capsule.jpg", icon: "Package", medicineCount: medicines.filter(m => m.category === "Tibbiy buyumlar").length },
  { id: "cat-35", name: "O'simlik preparatlari", slug: "osimlik-preparatlari", description: "O'simlik asosidagi preparatlar", image: "/images/medicines/paracetamol.jpg", icon: "Leaf", medicineCount: medicines.filter(m => m.category === "O'simlik preparatlari").length },
  { id: "cat-36", name: "Uy sharoitida davolash", slug: "uy-sharoitida-davolash", description: "Uy sharoitida davolash vositalari", image: "/images/medicines/paracetamol.jpg", icon: "Home", medicineCount: medicines.filter(m => m.category === "Uy sharoitida davolash").length },
  { id: "cat-37", name: "Ayollar salomatligi", slug: "ayollar-salomatligi", description: "Ayollar salomatligi uchun preparatlar", image: "/images/medicines/suppository.jpg", icon: "Heart", medicineCount: medicines.filter(m => m.category === "Ayollar salomatligi").length },
  { id: "cat-38", name: "Bolalar salomatligi", slug: "bolalar-salomatligi", description: "Bolalar salomatligi preparatlari", image: "/images/medicines/syrup.jpg", icon: "Baby", medicineCount: medicines.filter(m => m.category === "Bolalar salomatligi").length },
  { id: "cat-39", name: "Keksalik salomatlik", slug: "keksalik-salomatlik", description: "Keksalar salomatligi uchun", image: "/images/medicines/capsule.jpg", icon: "Users", medicineCount: medicines.filter(m => m.category === "Keksalik salomatlik").length },
  { id: "cat-40", name: "Hayvonlar uchun", slug: "hayvonlar-uchun", description: "Veterinariya preparatlari", image: "/images/medicines/tablets.jpg", icon: "PawPrint", medicineCount: medicines.filter(m => m.category === "Hayvonlar uchun").length },
  { id: "cat-41", name: "Parfyumeriya", slug: "parfyumeriya", description: "Parfyumeriya mahsulotlari", image: "/images/medicines/spray.jpg", icon: "Sparkles", medicineCount: medicines.filter(m => m.category === "Parfyumeriya").length },
  { id: "cat-42", name: "Tish og'riq", slug: "tish-ogriq", description: "Tish og'riq uchun dorilar", image: "/images/medicines/gel.jpg", icon: "Smile", medicineCount: medicines.filter(m => m.category === "Tish og'riq").length },
  { id: "cat-43", name: "Oshqozon", slug: "oshqozon", description: "Oshqozon kasalliklari uchun", image: "/images/medicines/capsule.jpg", icon: "Stethoscope", medicineCount: medicines.filter(m => m.category === "Oshqozon").length },
];

export const testimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Zebo Karimova",
    photo: "/images/testimonial-1.svg",
    role: "Bemor",
    rating: 5,
    content: "Bu platforma mening oilamning sog'lig'ini boshqarish usulini butunlay o'zgartirdi. Dori yetkazib berish juda tez va narxlar eng yaxshisi.",
  },
  {
    id: "test-2",
    name: "Ravshan Akramov",
    photo: "/images/testimonial-2.svg",
    role: "Bemor",
    rating: 5,
    content: "Onlayn maslahat xizmati menga juda ko'p vaqtni tejadi. 15 daqiqa ichida shifokor bilan video qo'ng'iroq qildim va o'sha kuni retsept bo'yicha dori oldim.",
  },
  {
    id: "test-3",
    name: "Malika Yusupova",
    photo: "/images/testimonial-3.svg",
    role: "Bemor",
    rating: 5,
    content: "Dorixonalardagi narxlarni solishtirish imkoniyati juda zo'r. Oylik dorilarimga kamida 30% tejayman.",
  },
  {
    id: "test-4",
    name: "Dilmurod Norboyev",
    photo: "/images/testimonial-4.svg",
    role: "Bemor",
    rating: 4,
    content: "Ajoyib xizmat! Dori qabul qilish eslatmalari juda foydali. Ilova intuitiv va yetkazib berishni kuzatish juda aniq.",
  },
];

export const faqs: FAQ[] = [
  {
    id: "faq-1",
    question: "Dori vositalariga qanday buyurtma beraman?",
    answer: "Sizga kerakli dorini qidiring, turli dorixonalardagi narxlarni solishtiring, savatga qo'shing va buyurtma bering. Resept talab qilinadigan dorilar uchun retseptni yuklashingiz mumkin.",
    category: "Buyurtmalar",
  },
  {
    id: "faq-2",
    question: "Barcha dorilar uchun retsept kerakmi?",
    answer: "Yo'q, faqat retsept bo'yicha dorilar uchun litsenziyali shifokordan retsept talab qilinadi. Reseptsiz dorilarni hech qanday hujjatsiz buyurtma qilish mumkin.",
    category: "Dorilar",
  },
  {
    id: "faq-3",
    question: "Yetkazib berish qancha vaqt oladi?",
    answer: "Yetkazib berish vaqti dorixonaga va joylashuvingizga qarab 20 daqiqadan 2 soatgacha davom etadi. Buyurtma berish jarayonida har bir dorixona uchun taxminiy yetkazib berish vaqtini ko'rishingiz mumkin.",
    category: "Yetkazib berish",
  },
  {
    id: "faq-4",
    question: "Onlayn shifokor bilan maslahatlasha olamanmi?",
    answer: "Ha! Biz turli mutaxassislikdagi litsenziyali shifokorlar bilan video va chat maslahatlarini taklif qilamiz. Uyingizdan chiqmasdan uchrashuv yozilib, shifokor bilan gaplashishingiz mumkin.",
    category: "Maslahat",
  },
  {
    id: "faq-5",
    question: "Narxlarni solishtirish qanday ishlaydi?",
    answer: "Dori vositasini qidirganingizda, sizning hududingizdagi bir nechta dorixonalarning narxlarini ko'rsatamiz. Eng yaxshi variantni tanlash uchun narxlar, yetkazib berish to'lovlari va taxminiy yetkazib berish vaqtlarini solishtirishingiz mumkin.",
    category: "Narxlar",
  },
  {
    id: "faq-6",
    question: "Qanday to'lov usullari qabul qilinadi?",
    answer: "Biz kredit/debet kartalari, mobil to'lov tizimlari va naqd pul to'lovlarini qabul qilamiz. Barcha tranzaksiyalar xavfsiz va shifrlangan.",
    category: "To'lovlar",
  },
  {
    id: "faq-7",
    question: "Dorilarni qaytarish mumkinmi?",
    answer: "Xavfsizlik va sog'liq qoidalariga ko'ra, dorilar yetkazib berilgandan keyin qaytarib olinmaydi. Agar shikastlangan yoki noto'g'ri mahsulot olgan bo'lsangiz, 24 soat ichida bizning qo'llab-quvvatlash guruhimizga murojaat qiling.",
    category: "Qaytarish",
  },
  {
    id: "faq-8",
    question: "Retseptni qanday yuklashim mumkin?",
    answer: "Retsept bo'yicha dorilarni buyurtma qilishda sizdan retseptning aniq suratini yuklashingiz so'raladi. Farmatsevtlar buyurtmani qayta ishlashdan oldin uni tekshiradi.",
    category: "Reseptlar",
  },
];

export const orders: Order[] = [
  {
    id: "ord-1",
    userId: "user-1",
    pharmacyId: "ph-1",
    pharmacyName: "Farmalife Dorixona",
    items: [
      {
        id: "item-1",
        medicineId: "med-1",
        medicineName: "Paratsetamol 500mg",
        medicineImage: "/images/medicine-1.svg",
        dosage: "500mg",
        quantity: 2,
        unitPrice: 5000,
        totalPrice: 10000,
        prescriptionRequired: false,
      },
      {
        id: "item-2",
        medicineId: "med-2",
        medicineName: "Ibuprofen 400mg",
        medicineImage: "/images/medicine-2.svg",
        dosage: "400mg",
        quantity: 1,
        unitPrice: 15000,
        totalPrice: 15000,
        prescriptionRequired: false,
      },
    ],
    status: "delivered",
    total: 25000,
    subtotal: 25000,
    deliveryFee: 0,
    discount: 0,
    tax: 0,
    deliveryAddress: {
      id: "addr-1",
      label: "Uy",
      fullName: "Ali Valiyev",
      phone: "+998 90 123-45-67",
      street: "Chilonzor-5, 23-uy",
      city: "Toshkent",
      state: "Chilonzor tumani",
      zipCode: "100000",
      isDefault: true,
    },
    paymentMethod: "Visa xxxx 4242",
    paymentStatus: "paid",
    estimatedDelivery: "2024-11-10T14:30:00",
    deliveredAt: "2024-11-10T14:15:00",
    tracking: [
      { status: "confirmed", timestamp: "2024-11-10T13:00:00", description: "Buyurtma tasdiqlandi" },
      { status: "preparing", timestamp: "2024-11-10T13:15:00", description: "Buyurtma tayyorlanmoqda" },
      { status: "picked-up", timestamp: "2024-11-10T13:45:00", description: "Buyurtma kuryer tomonidan olindi" },
      { status: "in-transit", timestamp: "2024-11-10T14:00:00", description: "Buyurtma yo'lda", location: "Amir Temur ko'chasi" },
      { status: "delivered", timestamp: "2024-11-10T14:15:00", description: "Buyurtma yetkazib berildi" },
    ],
    createdAt: "2024-11-10T13:00:00",
    updatedAt: "2024-11-10T14:15:00",
  },
  {
    id: "ord-2",
    userId: "user-1",
    pharmacyId: "ph-3",
    pharmacyName: "Sog'lik Dorixona",
    items: [
      {
        id: "item-3",
        medicineId: "med-5",
        medicineName: "Omeprazol 20mg",
        medicineImage: "/images/medicine-3.svg",
        dosage: "20mg",
        quantity: 1,
        unitPrice: 18000,
        totalPrice: 18000,
        prescriptionRequired: false,
      },
    ],
    status: "in-transit",
    total: 18000,
    subtotal: 18000,
    deliveryFee: 0,
    discount: 0,
    tax: 0,
    deliveryAddress: {
      id: "addr-1",
      label: "Uy",
      fullName: "Ali Valiyev",
      phone: "+998 90 123-45-67",
      street: "Chilonzor-5, 23-uy",
      city: "Toshkent",
      state: "Chilonzor tumani",
      zipCode: "100000",
      isDefault: true,
    },
    paymentMethod: "Mastercard xxxx 1234",
    paymentStatus: "paid",
    estimatedDelivery: "2024-11-15T11:30:00",
    tracking: [
      { status: "confirmed", timestamp: "2024-11-15T10:00:00", description: "Buyurtma tasdiqlandi" },
      { status: "preparing", timestamp: "2024-11-15T10:20:00", description: "Buyurtma tayyorlanmoqda" },
      { status: "picked-up", timestamp: "2024-11-15T10:50:00", description: "Buyurtma kuryer tomonidan olindi" },
      { status: "in-transit", timestamp: "2024-11-15T11:05:00", description: "Buyurtma yo'lda", location: "Navoiy ko'chasi" },
    ],
    createdAt: "2024-11-15T10:00:00",
    updatedAt: "2024-11-15T11:05:00",
  },
];

export const appointments: Appointment[] = [
  {
    id: "apt-1",
    doctorId: "doc-1",
    doctorName: "Dr. Akbar Karimov",
    doctorPhoto: "/images/doctor-1.svg",
    doctorSpecialty: "Terapevt",
    userId: "user-1",
    date: "2024-11-12",
    startTime: "10:00",
    endTime: "10:30",
    type: "video",
    status: "completed",
    reason: "Yillik tekshiruv",
    fee: 80000,
    paymentStatus: "paid",
    meetLink: "https://meet.vitahub.uz/apt-1",
    createdAt: "2024-11-10T08:00:00",
    updatedAt: "2024-11-12T10:30:00",
  },
  {
    id: "apt-2",
    doctorId: "doc-2",
    doctorName: "Dr. Lola Rahmonova",
    doctorPhoto: "/images/doctor-2.svg",
    doctorSpecialty: "Kardiolog",
    userId: "user-1",
    date: "2024-11-18",
    startTime: "09:30",
    endTime: "10:00",
    type: "video",
    status: "scheduled",
    reason: "Yurak tekshiruvi",
    fee: 120000,
    paymentStatus: "paid",
    createdAt: "2024-11-14T09:00:00",
    updatedAt: "2024-11-14T09:00:00",
  },
];

export const loyaltyPoints = {
  total: 1250,
  earned: 1500,
  redeemed: 250,
  tier: "gold" as const,
  pointsUntilNextTier: 750,
};

export const notifications = [
  {
    id: "notif-1",
    title: "Buyurtma yetkazib berildi",
    message: "Farmalife Dorixonadan buyurtmangiz muvaffaqiyatli yetkazib berildi.",
    type: "order" as const,
    isRead: false,
    createdAt: "2024-11-10T14:15:00",
  },
  {
    id: "notif-2",
    title: "Uchrashuv eslatmasi",
    message: "Dr. Akbar Karimov bilan video maslahatingiz ertaga 10:00 da.",
    type: "appointment" as const,
    isRead: false,
    createdAt: "2024-11-11T09:00:00",
  },
  {
    id: "notif-3",
    title: "Narx pasayishi haqida xabar",
    message: "Paratsetamol 500mg narxi Sog'lik Dorixonada 15% ga kamaydi.",
    type: "promotion" as const,
    isRead: true,
    createdAt: "2024-11-09T12:00:00",
  },
  {
    id: "notif-4",
    title: "Dori eslatmasi",
    message: "Omeprazol 20mg qabul qilish vaqti.",
    type: "reminder" as const,
    isRead: true,
    createdAt: "2024-11-15T08:00:00",
  },
];

export const savedAddresses = [
  {
    id: "addr-1",
    label: "Uy",
    fullName: "Ali Valiyev",
    phone: "+998 90 123-45-67",
    street: "Chilonzor-5, 23-uy, 5-xonadon",
    city: "Toshkent",
    state: "Chilonzor tumani",
    zipCode: "100042",
    isDefault: true,
  },
  {
    id: "addr-2",
    label: "Ish",
    fullName: "Ali Valiyev",
    phone: "+998 90 123-45-67",
    street: "Amir Temur shoh ko'chasi, 100-uy, 7-ofis",
    city: "Toshkent",
    state: "Mirobod tumani",
    zipCode: "100084",
    isDefault: false,
  },
];

export const paymentMethods = [
  {
    id: "pm-1",
    type: "Visa",
    lastFour: "4242",
    expiryDate: "12/26",
    isDefault: true,
  },
  {
    id: "pm-2",
    type: "Mastercard",
    lastFour: "1234",
    expiryDate: "08/25",
    isDefault: false,
  },
];

export const dashboardStats = {
  totalRevenue: 128450000,
  totalOrders: 3420,
  totalCustomers: 12500,
  totalDoctors: 48,
  totalMedicines: medicines.length,
  totalPharmacies: pharmacies.length,
  totalAppointments: 890,
  pendingOrders: 45,
  monthlyRevenue: [28500000, 32000000, 29800000, 34500000, 31000000, 35600000, 33400000, 37800000, 36200000, 39500000, 41200000, 42800000],
  monthlyOrders: [220, 245, 268, 290, 275, 310, 298, 330, 315, 350, 365, 380],
  popularMedicines: [
    { name: "Paratsetamol 500mg", count: 1250 },
    { name: "Ibuprofen 400mg", count: 980 },
    { name: "Vitamin D3", count: 850 },
    { name: "Amoksitsillin 500mg", count: 720 },
    { name: "Tsitirizin 10mg", count: 650 },
  ],
  revenueByPharmacy: [
    { name: "Farmalife", revenue: 45200000 },
    { name: "Sog'lik", revenue: 38900000 },
    { name: "Dorixona 777", revenue: 28400000 },
    { name: "Aziza Dorixona", revenue: 15950000 },
  ],
};

export const medicalRecords: MedicalRecord[] = [
  {
    id: "rec-1",
    userId: "user-1",
    title: "Yillik jismoniy tekshiruv",
    description: "To'liq tibbiy ko'rik natijalari",
    type: "diagnosis",
    date: "2024-10-15",
    doctorName: "Dr. Akbar Karimov",
    hospitalName: "Toshkent shahar 1-sonli poliklinika",
  },
  {
    id: "rec-2",
    userId: "user-1",
    title: "Qon tahlili natijalari",
    description: "Umumiy qon tahlili va biokimyoviy ko'rsatkichlar",
    type: "lab-report",
    date: "2024-10-15",
    doctorName: "Dr. Akbar Karimov",
    hospitalName: "Toshkent shahar 1-sonli poliklinika",
  },
  {
    id: "rec-3",
    userId: "user-1",
    title: "Omeprazol retsepti",
    description: "Oshqozon yonishi uchun retsept",
    type: "prescription",
    date: "2024-11-01",
    doctorName: "Dr. Akbar Karimov",
  },
];

export const getCategoryIcon = (icon: string): string => {
  const iconMap: Record<string, string> = {
    Activity: "Activity",
    Shield: "Shield",
    Heart: "Heart",
    Droplet: "Droplet",
    Wind: "Wind",
    Stethoscope: "Stethoscope",
    Apple: "Apple",
  };
  return iconMap[icon] || "Pill";
};
