#!/usr/bin/env python3
"""Final generator: ALL categories + 30k medicines."""
import json
import random
random.seed(42)

ALL_CATEGORIES = {
    # ═══ ORIGINAL CATEGORIES ═══
    "Og'riq qoldiruvchi": [
        ("Paratsetamol", "Paratsetamol", ["200mg", "250mg", "500mg", "1g"], ["tabletka", "suspenziya", "sirop"]),
        ("Ibuprofen", "Ibuprofen", ["200mg", "400mg", "600mg"], ["tabletka", "kapsula", "gel"]),
        ("Nurofen", "Ibuprofen", ["200mg", "400mg"], ["tabletka", "kapsula"]),
        ("Diklofenak", "Diklofenak", ["25mg", "50mg", "100mg"], ["tabletka", "kapsula", "gel"]),
        ("Ketorolak", "Ketorolak", ["10mg"], ["tabletka", "in'ektsiya"]),
        ("Analgin", "Metamizol natriy", ["500mg"], ["tabletka", "in'ektsiya"]),
        ("Nimesulid", "Nimesulid", ["100mg"], ["tabletka", "gel"]),
        ("Piroksikam", "Piroksikam", ["10mg", "20mg"], ["tabletka", "gel"]),
        ("Ketoprofen", "Ketoprofen", ["25mg", "50mg", "100mg"], ["tabletka", "kapsula", "gel"]),
        ("Flurbiprofen", "Flurbiprofen", ["50mg", "100mg"], ["tabletka"]),
        ("Lornoksikam", "Lornoksikam", ["4mg", "8mg"], ["tabletka", "in'ektsiya"]),
        ("Deksametazon", "Deksametazon", ["0.5mg", "4mg", "8mg"], ["tabletka", "in'ektsiya"]),
        ("Prednizolon", "Prednizolon", ["5mg", "10mg", "20mg", "50mg"], ["tabletka", "in'ektsiya"]),
        ("Metildop", "Metildop", ["250mg"], ["tabletka"]),
    ],
    "Antibiotiklar": [
        ("Amoksitsillin", "Amoksitsillin", ["250mg", "500mg", "1g"], ["tabletka", "kapsula", "suspenziya"]),
        ("Azitromitsin", "Azitromitsin", ["250mg", "500mg"], ["tabletka", "kapsula"]),
        ("Seftriakson", "Seftriakson", ["250mg", "500mg", "1g", "2g"], ["in'ektsiya"]),
        ("Tsiprofloksatsin", "Tsiprofloksatsin", ["250mg", "500mg", "750mg"], ["tabletka", "in'ektsiya"]),
        ("Doksitsiklin", "Doksitsiklin", ["100mg"], ["tabletka", "kapsula"]),
        ("Klaritromitsin", "Klaritromitsin", ["250mg", "500mg"], ["tabletka"]),
        ("Flemoksin", "Amoksitsillin", ["250mg", "500mg", "1g"], ["tabletka"]),
        ("Supraks", "Tsefiksim", ["200mg", "400mg"], ["kapsula", "suspenziya"]),
        ("Abaktal", "Tsefpoksim", ["200mg", "400mg"], ["tabletka"]),
        ("Ampitsillin", "Ampitsillin", ["250mg", "500mg"], ["tabletka", "kapsula"]),
        ("Gentamitsin", "Gentamitsin", ["40mg", "80mg"], ["in'ektsiya"]),
        ("Eritromitsin", "Eritromitsin", ["250mg", "500mg"], ["tabletka"]),
        ("Metronidazol", "Metronidazol", ["250mg", "500mg"], ["tabletka", "in'ektsiya"]),
        ("Klindamitsin", "Klindamitsin", ["150mg", "300mg"], ["kapsula"]),
        ("Norfloksatsin", "Norfloksatsin", ["400mg"], ["tabletka"]),
        ("Levofloksatsin", "Levofloksatsin", ["250mg", "500mg", "750mg"], ["tabletka", "in'ektsiya"]),
        ("Moksifloksatsin", "Moksifloksatsin", ["400mg"], ["tabletka"]),
        ("Imipenem", "Imipenem", ["500mg", "1g"], ["in'ektsiya"]),
        ("Meropenem", "Meropenem", ["1g"], ["in'ektsiya"]),
        ("Vankomitsin", "Vankomitsin", ["500mg", "1g"], ["in'ektsiya"]),
        ("Linezolid", "Linezolid", ["400mg", "600mg"], ["tabletka"]),
        ("Ko-trimoksazol", "Sulfametoksazol", ["480mg", "960mg"], ["tabletka"]),
        ("Furatsilin", "Nitrofural", ["0.2%"], ["eritma"]),
        ("Kloramfenikol", "Kloramfenikol", ["250mg", "500mg"], ["tabletka"]),
        ("Neomitsin", "Neomitsin", ["500mg"], ["tabletka", "maz"]),
    ],
    "Yurak-qon tomir": [
        ("Amlodipin", "Amlodipin", ["5mg", "10mg"], ["tabletka"]),
        ("Enalapril", "Enalapril", ["5mg", "10mg", "20mg"], ["tabletka"]),
        ("Lisinopril", "Lisinopril", ["5mg", "10mg", "20mg"], ["tabletka"]),
        ("Losartan", "Losartan", ["50mg", "100mg"], ["tabletka"]),
        ("Valsartan", "Valsartan", ["80mg", "160mg", "320mg"], ["tabletka"]),
        ("Bisoprolol", "Bisoprolol", ["2.5mg", "5mg", "10mg"], ["tabletka"]),
        ("Metoprolol", "Metoprolol", ["25mg", "50mg", "100mg"], ["tabletka"]),
        ("Atenolol", "Atenolol", ["25mg", "50mg", "100mg"], ["tabletka"]),
        ("Verapamil", "Verapamil", ["40mg", "80mg"], ["tabletka"]),
        ("Diltiazem", "Diltiazem", ["60mg", "90mg", "120mg"], ["tabletka"]),
        ("Nitroglycerin", "Nitroglycerin", ["0.5mg"], ["tabletka", "sprey"]),
        ("Validol", "Validol", ["60mg"], ["tabletka"]),
        ("Kordaron", "Amiodaron", ["200mg"], ["tabletka"]),
        ("Diroton", "Lizinopril", ["5mg", "10mg", "20mg"], ["tabletka"]),
        ("Prestarium", "Perindopril", ["5mg", "10mg"], ["tabletka"]),
        ("Norvasc", "Amlodipin", ["5mg", "10mg"], ["tabletka"]),
        ("Concor", "Bisoprolol", ["2.5mg", "5mg", "10mg"], ["tabletka"]),
        ("Corvalol", "Etamil bromizovalerianat", ["25ml"], ["eritma"]),
        ("Aspirin Cardio", "Acetilsalitsil kislota", ["100mg"], ["tabletka"]),
        ("Clopidogrel", "Klopidogrel", ["75mg"], ["tabletka"]),
        ("Kardiomagnil", "Acetilsalitsil kislota", ["75mg", "150mg"], ["tabletka"]),
        ("Warfarin", "Varfarin", ["2.5mg", "5mg"], ["tabletka"]),
        ("Dabigatran", "Dabigatran", ["75mg", "110mg", "150mg"], ["kapsula"]),
        ("Rivaroksaban", "Rivaroksaban", ["10mg", "15mg", "20mg"], ["tabletka"]),
        ("Atorvastatin", "Atorvastatin", ["10mg", "20mg", "40mg"], ["tabletka"]),
        ("Rosuvastatin", "Rosuvastatin", ["5mg", "10mg", "20mg"], ["tabletka"]),
        ("Simvastatin", "Simvastatin", ["10mg", "20mg", "40mg"], ["tabletka"]),
    ],
    "Ovqat hazm qilish": [
        ("Omeprazol", "Omeprazol", ["20mg", "40mg"], ["kapsula"]),
        ("Pantoprazol", "Pantoprazol", ["20mg", "40mg"], ["tabletka"]),
        ("Famotidin", "Famotidin", ["20mg", "40mg"], ["tabletka"]),
        ("Ranitidin", "Ranitidin", ["150mg", "300mg"], ["tabletka"]),
        ("Maalox", "Alüminiy gidroksidi", ["20ml"], ["suspenziya"]),
        ("Almagel", "Alüminiy gidroksidi", ["170ml"], ["suspenziya"]),
        ("Gaviscon", "Natriy alginat", ["10ml"], ["suspenziya"]),
        ("Smecta", "Diosmektit", ["3g"], ["paket"]),
        ("Enterosgel", "Metilsilatik kislota", ["225g"], ["gel"]),
        ("Polysorb", "Kolloidli silika", ["3g", "6g"], ["paket"]),
        ("Lactofiltrum", "Laktuloza/Lignin", ["375mg"], ["tabletka"]),
        ("Fosfalugel", "Alüminiy fosfat", ["16g"], ["gel"]),
        ("De-Nol", "Vismut subtsitrat", ["120mg"], ["tabletka"]),
        ("Creon", "Pancreatin", ["10000", "25000"], ["kapsula"]),
        ("Mezim", "Pancreatin", ["10000"], ["tabletka"]),
        ("Festal", "Pancreatin/Hemitsellulaz", ["tabletka"]),
        ("Trimedat", "Trimebutin", ["100mg", "200mg"], ["tabletka"]),
        ("Duspatalin", "Mebeverin", ["135mg", "200mg"], ["tabletka"]),
        ("No-Spa", "Drotaverin", ["40mg"], ["tabletka"]),
        ("Buscopan", "Hüskopolin bromid", ["10mg"], ["tabletka"]),
        ("Loperamid", "Loperamid", ["2mg"], ["tabletka"]),
        ("Imodium", "Loperamid", ["2mg"], ["kapsula"]),
        ("Linex", "Laktobatsilluslar", ["kapsula"]),
        ("Bifiform", "Bifidobakteriyalar", ["kapsula"]),
        ("Acipol", "Acidofilus", ["kapsula"]),
        ("Hilak Forte", "Metabolitlar", ["30ml"], ["eritma"]),
        ("Motilium", "Domperidon", ["10mg"], ["tabletka"]),
        ("Zeercal", "Metoklopramid", ["10mg"], ["tabletka"]),
    ],
    "Vitaminlar": [
        ("Vitamin D3", "Kolekalsiferol", ["1000 IU", "2000 IU", "5000 IU"], ["tabletka", "kapsula"]),
        ("Vitamin C", "Askorbin kislota", ["250mg", "500mg", "1g"], ["tabletka", "sharbat"]),
        ("Vitamin B12", "Kobalamin", ["1000mcg", "5000mcg"], ["tabletka", "in'ektsiya"]),
        ("Vitamin B6", "Piridoksin", ["50mg", "100mg"], ["tabletka"]),
        ("Vitamin B1", "Tiamin", ["100mg"], ["tabletka"]),
        ("Vitamin E", "Tokoferol", ["100 IU", "200 IU"], ["kapsula"]),
        ("Vitamin A", "Retinol", ["25000 IU"], ["kapsula"]),
        ("Supradyn", "Multivitamin", ["tabletka"]),
        ("Duovit", "Multivitamin", ["tabletka"]),
        ("Multitabs", "Multivitamin", ["tabletka"]),
        ("Revit", "Multivitamin", ["tabletka"]),
        ("Gendevit", "Multivitamin", ["tabletka"]),
        ("Complivit", "Multivitamin", ["tabletka"]),
        ("Centrum", "Multivitamin", ["tabletka"]),
        ("Alphabet", "Multivitamin", ["tabletka"]),
        ("Magnelis B6", "Magniy/Piridoksin", ["40mg"], ["tabletka"]),
        ("Calcemin", "Kaltsiy/Vitamin D", ["tabletka"]),
        ("Teraflex", "Glükozamin/Chondroitin", ["kapsula"]),
        ("Doppelherz", "Multivitamin", ["tabletka", "kapsula"]),
        ("Elevit", "Multivitamin", ["tabletka"]),
    ],
    "Nafas olish": [
        ("Salbutamol", "Salbutamol", ["100mcg", "200mcg"], ["sprey", "nebulizatsiya"]),
        ("Berodual", "Ipratropiy/Fenoterol", ["20ml"], ["eritma"]),
        ("Pulmicort", "Budezonid", ["0.25mg", "0.5mg"], ["nebulizatsiya"]),
        ("Fliksotid", "Flutikazon", ["50mcg", "125mcg"], ["sprey"]),
        ("Singulair", "Montelukast", ["4mg", "5mg", "10mg"], ["tabletka"]),
        ("Eufillin", "Eofillin", ["100mg", "200mg"], ["tabletka", "in'ektsiya"]),
        ("Ambroksol", "Ambroksol", ["30mg", "60mg"], ["tabletka", "sirop"]),
        ("Lazolvan", "Ambroksol", ["30mg", "75mg"], ["tabletka", "sirop"]),
        ("ACC", "Atsetilsistein", ["100mg", "200mg", "600mg"], ["tabletka", "paket"]),
        ("Erespal", "Fenspirid", ["80mg"], ["tabletka", "sirop"]),
        ("Herbion", "Plantain/Primula", ["sirop"]),
        ("Prospan", "Efeushya", ["sirop"]),
        ("Gedelix", "Efira", ["sirop"]),
        ("Travisil", "Homeopatik", ["pastilka"]),
        ("Cinnabsin", "Homeopatik", ["tabletka"]),
        ("Sinupret", "Homeopatik", ["tabletka", "tomchi"]),
    ],
    "Qandli diabet": [
        ("Metformin", "Metformin", ["500mg", "850mg", "1000mg"], ["tabletka"]),
        ("Glucophage", "Metformin", ["500mg", "850mg", "1000mg"], ["tabletka"]),
        ("Siofor", "Metformin", ["500mg", "850mg", "1000mg"], ["tabletka"]),
        ("Glibenclamid", "Glibenclamid", ["5mg"], ["tabletka"]),
        ("Glimepirid", "Glimepirid", ["1mg", "2mg", "3mg", "4mg"], ["tabletka"]),
        ("Amaril", "Glimepirid", ["1mg", "2mg", "3mg", "4mg"], ["tabletka"]),
        ("Januvia", "Sitagliptin", ["25mg", "50mg", "100mg"], ["tabletka"]),
        ("Galvus", "Vildagliptin", ["50mg"], ["tabletka"]),
        ("Ongliza", "Saxagliptin", ["2.5mg", "5mg"], ["tabletka"]),
        ("Victoza", "Liraglutid", ["6mg/ml"], ["in'ektsiya"]),
        ("Insulin NovoRapid", "Insulin aspart", ["100 IU/ml"], ["in'ektsiya"]),
        ("Insulin Lantus", "Insulin glargine", ["100 IU/ml"], ["in'ektsiya"]),
        ("Insulin Humalog", "Insulin lyspro", ["100 IU/ml"], ["in'ektsiya"]),
        ("Diabeton", "Gliklazid", ["80mg"], ["tabletka"]),
        ("Reklid", "Gliklazid", ["80mg"], ["tabletka"]),
    ],
    "Allergiyaga qarshi": [
        ("Cetirizin", "Setirizin", ["5mg", "10mg"], ["tabletka", "tomchi"]),
        ("Loratadin", "Loratadin", ["10mg"], ["tabletka"]),
        ("Desloratadin", "Desloratadin", ["5mg"], ["tabletka"]),
        ("Feksofenadin", "Feksofenadin", ["120mg", "180mg"], ["tabletka"]),
        ("Levotsetirizin", "Levotsetirizin", ["5mg"], ["tabletka"]),
        ("Suprastin", "Kloropiramin", ["25mg"], ["tabletka"]),
        ("Difenhidramin", "Difenhidramin", ["50mg"], ["tabletka"]),
        ("Ketotifen", "Ketotifen", ["1mg"], ["tabletka"]),
        ("Montelukast", "Montelukast", ["4mg", "5mg", "10mg"], ["tabletka"]),
        ("Fenistil", "Dimetinden", ["0.1%"], ["gel"]),
    ],
    "Gormonlar": [
        ("L-tiroksin", "Levotiroksin", ["25mcg", "50mcg", "100mcg"], ["tabletka"]),
        ("Eutiroks", "Levotiroksin", ["25mcg", "50mcg", "100mcg"], ["tabletka"]),
        ("Prednizolon", "Prednizolon", ["5mg"], ["tabletka"]),
        ("Deksametazon", "Deksametazon", ["0.5mg"], ["tabletka"]),
        ("Hidrokortizon", "Hidrokortizon", ["20mg"], ["tabletka"]),
        ("Metipred", "Metilprednizolon", ["4mg", "8mg", "16mg"], ["tabletka"]),
        ("Provera", "Medroksiprogesteron", ["2.5mg", "5mg", "10mg"], ["tabletka"]),
        ("Duphaston", "Dydrogesteron", ["10mg"], ["tabletka"]),
        ("Utrozhestan", "Progesteron", ["100mg", "200mg"], ["kapsula"]),
        ("Clomid", "Klomifen", ["50mg"], ["tabletka"]),
    ],
    "Immunitet": [
        ("Interferon", "Interferon alfa-2b", ["in'ektsiya"]),
        ("Viferon", "Interferon alfa-2b", ["maz", "gel", "shamcha"]),
        ("Genferon", "Interferon alfa-2b", ["shamcha"]),
        ("Anaferon", "Homeopatik", ["tabletka"]),
        ("Ergoferon", "Homeopatik", ["tabletka"]),
        ("Arbidol", "Umifenovir", ["100mg", "200mg"], ["kapsula"]),
        ("Tamiflu", "Oseltamivir", ["30mg", "45mg", "75mg"], ["kapsula"]),
        ("Kagocel", "Kagotsel", ["12mg"], ["tabletka"]),
        ("Polyoxidonium", "Azoksimer bromid", ["6mg", "12mg"], ["tabletka"]),
        ("Immunal", "Echinacea purpurea", ["tomchi", "tabletka"]),
        ("Imudon", "Lizatlar", ["tabletka"]),
        ("IRS-19", "Bakterial lizatlar", ["sprey"]),
        ("Broncho-munal", "Bakterial lizatlar", ["kapsula"]),
        ("Ribomunil", "Bakterial ribosomalar", ["tabletka"]),
    ],
    "Teri kasalliklari": [
        ("Advantan", "Metilprednizolon", ["0.1%"], ["maz", "suspenziya"]),
        ("Elokom", "Mometazon", ["0.1%"], ["maz", "sprey"]),
        ("Triderm", "Klotrimazol/Gentamitsin", ["15g"], ["maz"]),
        ("Nizoral", "Ketokonazol", ["2%"], ["maz", "shampun"]),
        ("Lamisil", "Terbinofin", ["1%"], ["maz", "sprey"]),
        ("Exoderil", "Naftifin", ["1%"], ["maz", "eritma"]),
        ("Panthenol", "Dekspantenol", ["5%"], ["krem", "sprey"]),
        ("Bepanthen", "Dekspantenol", ["5%"], ["krem", "sprey"]),
        ("Levomekol", "Kloramfenikol/Metiluratsil", ["maz"]),
        ("Akriderm", "Betametazon", ["0.05%"], ["maz"]),
        ("Sinaflan", "Flutsinolon", ["0.025%"], ["maz"]),
        ("Oksolin", "Oksolin", ["0.25%"], ["maz"]),
    ],
    "Ko'z dorilari": [
        ("Tobrex", "Tobramitsin", ["0.3%"], ["damla"]),
        ("Albucid", "Sulfatsetamid", ["10%", "20%"], ["damla"]),
        ("Floksal", "Ofloksatsin", ["0.3%"], ["damla"]),
        ("Tobradex", "Tobramitsin/Deksametazon", ["damla"]),
        ("Ketotifen", "Ketotifen", ["0.025%"], ["damla"]),
        ("Vizin", "Tetrahüdrozolin", ["0.05%"], ["damla"]),
        ("Emoksipin", "Metiletilpiridinol", ["1%"], ["damla"]),
        ("Tauphon", "Taurin", ["4%"], ["damla"]),
        ("Irifrin", "Fenilefrin", ["2.5%", "10%"], ["damla"]),
        ("Cyclomed", "Tsiklopentolat", ["1%"], ["damla"]),
    ],
    "Nafas yo'llari": [
        ("Ambroksol", "Ambroksol", ["30mg", "60mg"], ["tabletka"]),
        ("ACC Long", "Atsetilsistein", ["600mg"], ["paket"]),
        ("Fluimutsil", "Atsetilsistein", ["600mg"], ["paket"]),
        ("Erespal", "Fenspirid", ["80mg"], ["tabletka"]),
        ("Ascoril", "Salbutamol/Bromheksin", ["sirop"]),
        ("Bronholitin", "Efedrin/Glautsin", ["sirop"]),
        ("Herbion", "Plantain/Primula", ["sirop"]),
        ("Prospan", "Efeushya", ["sirop"]),
        ("Gedelix", "Efira", ["sirop"]),
        ("Travisil", "Homeopatik", ["pastilka"]),
    ],
    "Otolaringologiya": [
        ("Otipax", "Fenazon/Lidokain", ["16ml"], ["damla"]),
        ("Garazon", "Betametazon/Gentamitsin", ["5ml"], ["damla"]),
        ("Normaks", "Norfloksatsin", ["0.3%"], ["damla"]),
        ("Tizin", "Tetrahüdrozolin", ["0.05%", "0.1%"], ["sprey"]),
        ("Nazivin", "Oksimetazolin", ["0.01%", "0.025%", "0.05%"], ["sprey"]),
        ("Naphthyzinum", "Nafazolin", ["0.05%", "0.1%"], ["sprey", "damla"]),
        ("Galazolin", "Ksillometazolin", ["0.05%", "0.1%"], ["sprey"]),
        ("Pinosol", "Pine/Eucalyptus", ["damla", "sprey"]),
        ("Geksoral", "Geksetidin", ["0.1%", "0.2%"], ["eritma", "sprey"]),
        ("Tantum Verde", "Bendazol", ["0.15%"], ["sprey"]),
        ("Strepsils", "Diklorobenzilmetanol", ["pastilka"]),
        ("Faringosept", "Ambazol", ["pastilka"]),
        ("Grammidin", "Gramitsidin", ["pastilka"]),
    ],
    "Asab tizimi": [
        ("Afobazol", "Fabomotizol", ["10mg"], ["tabletka"]),
        ("Grandaxin", "Tofizolam", ["50mg"], ["tabletka"]),
        ("Gidazepam", "Gidazepam", ["20mg"], ["tabletka"]),
        ("Phenibut", "Fenibut", ["250mg"], ["tabletka"]),
        ("Tenoten", "Homeopatik", ["tabletka"]),
        ("Nootropil", "Piratsetam", ["400mg", "800mg"], ["tabletka"]),
        ("Cinnarizin", "Tsinnarizin", ["25mg"], ["tabletka"]),
        ("Stugeron", "Tsinnarizin", ["25mg"], ["tabletka"]),
        ("Amitriptilin", "Amitriptilin", ["25mg", "50mg"], ["tabletka"]),
        ("Fluoksetin", "Fluoksetin", ["20mg"], ["kapsula"]),
        ("Sertralin", "Sertralin", ["50mg", "100mg"], ["tabletka"]),
        ("Escitalopram", "Escitalopram", ["5mg", "10mg", "20mg"], ["tabletka"]),
        ("Venlafaksin", "Venlafaksin", ["37.5mg", "75mg"], ["kapsula"]),
        ("Novo-Passit", "Valeriana/Humulus", ["tabletka", "eritma"]),
        ("Persen", "Valeriana/Melissa/Menta", ["kapsula"]),
        ("Valeriana", "Valeriana", ["tabletka", "tomchi"]),
    ],
    "Bolalar": [
        ("Paratsetamol bolalar", "Paratsetamol", ["100mg", "120mg"], ["suspenziya", "sirop"]),
        ("Ibuprofen bolalar", "Ibuprofen", ["100mg/5ml"], ["suspenziya"]),
        ("Nurofen bolalar", "Ibuprofen", ["100mg/5ml"], ["suspenziya"]),
        ("Cefekon", "Paratsetamol", ["100mg", "250mg"], ["shamcha"]),
        ("Viferon bolalar", "Interferon", ["shamcha"]),
        ("Anaferon bolalar", "Homeopatik", ["tabletka"]),
        ("Lazolvan bolalar", "Ambroksol", ["15mg/5ml"], ["sirop"]),
        ("ACC bolalar", "Atsetilsistein", ["100mg", "200mg"], ["paket"]),
        ("Prospan bolalar", "Efeushya", ["sirop"]),
        ("Smecta bolalar", "Diosmektit", ["3g"], ["paket"]),
        ("Linex bolalar", "Laktobatsilluslar", ["kapsula"]),
        ("Bifiform bolalar", "Bifidobakteriyalar", ["kapsula"]),
        ("Zodak bolalar", "Setirizin", ["5mg"], ["sprey", "tomchi"]),
        ("Zyrtec bolalar", "Setirizin", ["5mg"], ["tomchi"]),
    ],
    "Onkologiya": [
        ("Methotrexate", "Metotreksat", ["2.5mg", "5mg", "10mg"], ["tabletka", "in'ektsiya"]),
        ("Tamoxifen", "Tamoksifen", ["20mg"], ["tabletka"]),
        ("Anastrozol", "Anastrozol", ["1mg"], ["tabletka"]),
        ("Letrozol", "Letrozol", ["2.5mg"], ["tabletka"]),
        ("Capecitabine", "Kapetsitabin", ["150mg", "500mg"], ["tabletka"]),
        ("Imatinib", "Imatinib", ["100mg", "400mg"], ["tabletka"]),
        ("Erlotinib", "Erlotinib", ["100mg", "150mg"], ["kapsula"]),
        ("Sorafenib", "Sorafenib", ["200mg"], ["tabletka"]),
        ("Bortezomib", "Bortezomib", ["3.5mg"], ["in'ektsiya"]),
        ("Lenalidomide", "Lenalidomide", ["5mg", "10mg", "25mg"], ["kapsula"]),
        ("Temozolomide", "Temozolomid", ["20mg", "100mg"], ["kapsula"]),
        ("Pembrolizumab", "Pembrolizumab", ["25mg/ml"], ["in'ektsiya"]),
    ],
    "Ortopediya": [
        ("Diklofenak gel", "Diklofenak", ["1%", "5%"], ["gel", "maz"]),
        ("Ketonal", "Ketoprofen", ["100mg"], ["kapsula", "gel"]),
        ("Chondroitin", "Xondroitin sulfat", ["250mg", "500mg"], ["kapsula"]),
        ("Teraflex", "Glükozamin/Xondroitin", ["kapsula"]),
        ("Don", "Glükozamin", ["1500mg"], ["paket"]),
        ("Artra", "Xondroitin/Glükozamin", ["tabletka"]),
        ("Movalis", "Meloksikam", ["7.5mg", "15mg"], ["tabletka"]),
        ("Nimulid", "Nimesulid", ["100mg"], ["tabletka", "gel"]),
        ("Voltaren", "Diklofenak", ["25mg", "50mg"], ["tabletka", "gel"]),
        ("Naklofen", "Diklofenak", ["25mg", "50mg"], ["kapsula", "in'ektsiya"]),
        ("Arkoksia", "Etorikoksib", ["60mg", "90mg"], ["tabletka"]),
    ],
    "Ginekologiya": [
        ("Clotrimazole", "Klotrimazol", ["100mg", "500mg"], ["tabletka", "shamcha"]),
        ("Pimafucin", "Natamitsin", ["100mg"], ["shamcha"]),
        ("Terzhinan", "Nestatine/Ternidazol", ["shamcha"]),
        ("Geksikon", "Hlorgeksidin", ["0.05%"], ["eritma", "shamcha"]),
        ("Polygynax", "Neomitsin/Nystatin", ["shamcha"]),
        ("Klion", "Metronidazol", ["250mg"], ["tabletka"]),
        ("Trichopol", "Metronidazol", ["250mg", "500mg"], ["tabletka"]),
        ("Fluomizin", "Dequaliniy xlorid", ["10mg"], ["shamcha"]),
        ("Duphaston", "Dydrogesteron", ["10mg"], ["tabletka"]),
        ("Utrozhestan", "Progesteron", ["100mg", "200mg"], ["kapsula"]),
        ("Postinor", "Levonorgestrel", ["0.75mg"], ["tabletka"]),
        ("Yarina", "Drospirenon/Ethinylestradiol", ["tabletka"]),
    ],
    "Stomatologiya": [
        ("Metragil Dent", "Metronidazol", ["toothpaste"]),
        ("Lacalut", "Alüminiy laktat", ["toothpaste"]),
        ("Sensodyne", "Kaltsiy-fosfat", ["toothpaste"]),
        ("PresiDENT", "Ekstraktlar", ["toothpaste"]),
        ("Elmex", "Amin-ftorid", ["toothpaste"]),
        ("Parodontax", "Natriy bikarbonat", ["toothpaste"]),
        ("Chlorgeksidin", "Hlorgeksidin", ["0.05%"], ["eritma"]),
        ("Denta", "Triclosan", ["toothpaste"]),
    ],
    "Urologiya": [
        ("Canephron", "Centauriya/Meyron", ["tabletka", "tomchi"]),
        ("Cyston", "Homeopatik", ["tabletka"]),
        ("Monurel", "Kranberi", ["tabletka"]),
        ("Nitroksolin", "Nitroksolin", ["50mg"], ["tabletka"]),
        ("5-NOK", "Nitroksolin", ["50mg"], ["tabletka"]),
        ("Furadonin", "Nitrofurantoin", ["50mg", "100mg"], ["tabletka"]),
        ("Furagin", "Furazidin", ["50mg"], ["tabletka"]),
        ("Prostamol", "Serenoa ekstrakti", ["320mg"], ["kapsula"]),
        ("Vezikar", "Solifenacin", ["5mg", "10mg"], ["tabletka"]),
        ("Spasmex", "Trospiy xlorid", ["5mg", "10mg"], ["tabletka"]),
    ],
    "Qon topish": [
        ("Sorbifer", "Fumarat temir", ["tabletka"]),
        ("Ferum Lek", "Polimaltoz ferik", ["in'ektsiya"]),
        ("Tardiferon", "Fumarat temir", ["tabletka"]),
        ("Actiferrin", "Ferri sulyat", ["kapsula", "sirop"]),
        ("Ferrograd", "Sulfat temir", ["tabletka"]),
        ("Folik kislota", "Folik kislota", ["5mg"], ["tabletka"]),
        ("Tranexam", "Traneksam kislota", ["250mg", "500mg"], ["tabletka"]),
        ("Dicinon", "Etamsilat", ["250mg", "500mg"], ["tabletka"]),
        ("Vikasol", "Menadion natriy", ["10mg"], ["tabletka"]),
    ],
    # ═══ NEW CATEGORIES (20+) ═══
    "Revmatologiya": [
        ("Metotreksat", "Metotreksat", ["2.5mg", "7.5mg", "10mg", "15mg"], ["tabletka"]),
        ("Sulfasalazin", "Sulfasalazin", ["500mg"], ["tabletka"]),
        ("Leflunomid", "Leflunomid", ["10mg", "20mg"], ["tabletka"]),
        ("Hydroxychloroquine", "Gidroksixloroxin", ["200mg"], ["tabletka"]),
        ("Azathioprine", "Azatioprin", ["50mg"], ["tabletka"]),
        ("Cyclosporin", "Siklosporin", ["25mg", "50mg", "100mg"], ["kapsula"]),
        ("Adalimumab", "Adalimumab", ["40mg"], ["in'ektsiya"]),
        ("Etanercept", "Etanercept", ["25mg", "50mg"], ["in'ektsiya"]),
        ("Celecoxib", "Tseleoksib", ["100mg", "200mg"], ["kapsula"]),
        ("Etoricoxib", "Etorikoksib", ["60mg", "90mg", "120mg"], ["tabletka"]),
        ("Meloxicam", "Meloksikam", ["7.5mg", "15mg"], ["tabletka"]),
        ("Naproxen", "Naproksen", ["250mg", "500mg"], ["tabletka"]),
    ],
    "Endokrinologiya": [
        ("Mercazolil", "Tiamazol", ["5mg", "10mg"], ["tabletka"]),
        ("Tyrozol", "Tiamazol", ["10mg"], ["tabletka"]),
        ("Propitsil", "Propiltiouratsil", ["50mg", "100mg"], ["tabletka"]),
        ("Metformin", "Metformin", ["500mg", "850mg", "1000mg"], ["tabletka"]),
        ("Glucophage", "Metformin", ["500mg", "850mg"], ["tabletka"]),
        ("Diabeton", "Gliklazid", ["80mg"], ["tabletka"]),
        ("Januvia", "Sitagliptin", ["100mg"], ["tabletka"]),
        ("Xenical", "Orlistat", ["120mg"], ["kapsula"]),
        ("Insulin NovoRapid", "Insulin aspart", ["100 IU/ml"], ["in'ektsiya"]),
        ("Insulin Lantus", "Insulin glargine", ["100 IU/ml"], ["in'ektsiya"]),
        ("Insulin Humalog", "Insulin lyspro", ["100 IU/ml"], ["in'ektsiya"]),
        ("Insulin Actrapid", "Insulin inson", ["100 IU/ml"], ["in'ektsiya"]),
    ],
    "Gastroenterologiya": [
        ("Omeprazol", "Omeprazol", ["10mg", "20mg", "40mg"], ["kapsula"]),
        ("Pantoprazol", "Pantoprazol", ["20mg", "40mg"], ["tabletka"]),
        ("Rabeprazol", "Rabeprazol", ["10mg", "20mg"], ["tabletka"]),
        ("Esomeprazol", "Esomeprazol", ["20mg", "40mg"], ["tabletka"]),
        ("Lansoprazol", "Lansoprazol", ["15mg", "30mg"], ["kapsula"]),
        ("Famotidin", "Famotidin", ["20mg", "40mg"], ["tabletka"]),
        ("Ranitidin", "Ranitidin", ["150mg", "300mg"], ["tabletka"]),
        ("Maalox", "Alüminiy gidroksidi", ["suspenziya", "tabletka"]),
        ("Almagel", "Alüminiy gidroksidi", ["suspenziya"]),
        ("De-Nol", "Vismut subtsitrat", ["120mg"], ["tabletka"]),
        ("Smecta", "Diosmektit", ["3g"], ["paket"]),
        ("Enterosgel", "Metilsilatik kislota", ["225g"], ["gel"]),
        ("Creon", "Pancreatin", ["10000", "25000"], ["kapsula"]),
        ("Mezim", "Pancreatin", ["10000"], ["tabletka"]),
        ("Trimedat", "Trimebutin", ["100mg", "200mg"], ["tabletka"]),
        ("Duspatalin", "Mebeverin", ["135mg", "200mg"], ["tabletka"]),
        ("No-Spa", "Drotaverin", ["40mg"], ["tabletka"]),
        ("Loperamid", "Loperamid", ["2mg"], ["tabletka"]),
        ("Linex", "Laktobatsilluslar", ["kapsula"]),
        ("Bifiform", "Bifidobakteriyalar", ["kapsula"]),
        ("Motilium", "Domperidon", ["10mg"], ["tabletka"]),
        ("Ursosan", "Ursodeoksikholik kislota", ["250mg"], ["kapsula"]),
        ("Hofitol", "Artishok ekstrakti", ["200mg"], ["tabletka"]),
    ],
    "Nevrologiya": [
        ("Piratsetam", "Piratsetam", ["400mg", "800mg", "1200mg"], ["tabletka"]),
        ("Nootropil", "Piratsetam", ["400mg", "800mg"], ["tabletka"]),
        ("Cinnarizin", "Tsinnarizin", ["25mg"], ["tabletka"]),
        ("Stugeron", "Tsinnarizin", ["25mg"], ["tabletka"]),
        ("Vinpocetine", "Vintsetsin", ["5mg", "10mg"], ["tabletka"]),
        ("Cavinton", "Vintsetsin", ["5mg", "10mg"], ["tabletka"]),
        ("Sermion", "Nicergolin", ["5mg", "10mg"], ["tabletka"]),
        ("Glycine", "Glitsin", ["100mg"], ["tabletka"]),
        ("Phenibut", "Fenibut", ["250mg"], ["tabletka"]),
        ("Afobazol", "Fabomotizol", ["10mg"], ["tabletka"]),
        ("Grandaxin", "Tofizolam", ["50mg"], ["tabletka"]),
        ("Gabapentin", "Gabapentin", ["300mg", "600mg"], ["kapsula"]),
        ("Pregabalin", "Pregabalin", ["25mg", "75mg", "150mg"], ["kapsula"]),
        ("Carbamazepine", "Karbamazepin", ["200mg", "400mg"], ["tabletka"]),
        ("Valproic acid", "Natriy valproat", ["200mg", "500mg"], ["tabletka"]),
        ("Topiramate", "Topiramat", ["25mg", "50mg", "100mg"], ["tabletka"]),
        ("Lamotrigine", "Lamotrijin", ["25mg", "50mg"], ["tabletka"]),
        ("Levetiracetam", "Levetiratsetam", ["250mg", "500mg"], ["tabletka"]),
        ("Seduxen", "Diazepam", ["2mg", "5mg"], ["tabletka"]),
        ("Zolpidem", "Zolpidem", ["5mg", "10mg"], ["tabletka"]),
    ],
    "Psixiatriya": [
        ("Fluoksetin", "Fluoksetin", ["20mg"], ["kapsula"]),
        ("Sertralin", "Sertralin", ["50mg", "100mg"], ["tabletka"]),
        ("Escitalopram", "Escitalopram", ["5mg", "10mg", "20mg"], ["tabletka"]),
        ("Venlafaksin", "Venlafaksin", ["37.5mg", "75mg", "150mg"], ["kapsula"]),
        ("Duloksetin", "Duloksetin", ["30mg", "60mg"], ["kapsula"]),
        ("Paroxetine", "Paroksetin", ["10mg", "20mg"], ["tabletka"]),
        ("Citalopram", "Tsitalopram", ["10mg", "20mg"], ["tabletka"]),
        ("Mirtazapine", "Mirtazapin", ["15mg", "30mg"], ["tabletka"]),
        ("Amitriptyline", "Amitriptilin", ["10mg", "25mg", "50mg"], ["tabletka"]),
        ("Diazepam", "Diazepam", ["2mg", "5mg", "10mg"], ["tabletka"]),
        ("Alprazolam", "Alprazolam", ["0.25mg", "0.5mg", "1mg"], ["tabletka"]),
        ("Lorazepam", "Lorazepam", ["1mg", "2mg"], ["tabletka"]),
        ("Buspirone", "Buspiron", ["5mg", "10mg"], ["tabletka"]),
        ("Hydroxyzine", "Gidroksizin", ["25mg"], ["tabletka"]),
        ("Propranolol", "Propranolol", ["10mg", "40mg"], ["tabletka"]),
        ("Adaptol", "Mebikar", ["300mg", "500mg"], ["tabletka"]),
        ("Haloperidol", "Galoperidol", ["1.5mg", "5mg"], ["tabletka"]),
        ("Olanzapine", "Olanzapin", ["2.5mg", "5mg", "10mg"], ["tabletka"]),
        ("Quetiapine", "Ketiapin", ["25mg", "50mg", "100mg"], ["tabletka"]),
        ("Risperidone", "Risperidon", ["1mg", "2mg"], ["tabletka"]),
        ("Aripiprazole", "Aripiprazol", ["5mg", "10mg"], ["tabletka"]),
        ("Lithium carbonate", "Litsey karbonat", ["300mg"], ["tabletka"]),
    ],
    "Allergologiya": [
        ("Cetirizin", "Setirizin", ["5mg", "10mg"], ["tabletka"]),
        ("Loratadine", "Loratadin", ["10mg"], ["tabletka"]),
        ("Desloratadine", "Desloratadin", ["5mg"], ["tabletka"]),
        ("Fexofenadine", "Feksofenadin", ["120mg", "180mg"], ["tabletka"]),
        ("Levocetirizin", "Levotsetirizin", ["5mg"], ["tabletka"]),
        ("Chloropyramine", "Kloropiramin", ["25mg"], ["tabletka"]),
        ("Suprastin", "Kloropiramin", ["25mg"], ["tabletka"]),
        ("Diphenhydramine", "Difenhidramin", ["50mg"], ["tabletka"]),
        ("Ketotifen", "Ketotifen", ["1mg"], ["tabletka"]),
        ("Azelastine", "Azellastin", ["0.1%"], ["sprey", "damla"]),
        ("Montelukast", "Montelukast", ["4mg", "5mg", "10mg"], ["tabletka"]),
        ("Zafirlukast", "Zafirlukast", ["20mg"], ["tabletka"]),
        ("Cromoglicic acid", "Kromoglitsik kislota", ["20mg"], ["kapsula"]),
        ("Betamethasone", "Betametazon", ["0.5mg"], ["tabletka"]),
        ("Dexamethasone", "Deksametazon", ["0.5mg", "4mg"], ["tabletka"]),
        ("Prednisolone", "Prednizolon", ["5mg", "20mg"], ["tabletka"]),
        ("Clemastine", "Klemastin", ["1mg"], ["tabletka"]),
        ("Phencarol", "Sinkarol", ["25mg", "50mg"], ["tabletka"]),
    ],
    "Immunologiya": [
        ("Interferon alfa", "Interferon alfa-2b", ["3MIU"], ["in'ektsiya"]),
        ("Peginterferon", "Peginterferon", ["135mcg", "180mcg"], ["in'ektsiya"]),
        ("Ribavirin", "Ribavirin", ["200mg"], ["kapsula"]),
        ("Acyclovir", "Atsiklovir", ["200mg", "400mg", "800mg"], ["tabletka", "maz"]),
        ("Valacyclovir", "Valatsiklovir", ["500mg", "1000mg"], ["tabletka"]),
        ("Ganciclovir", "Gantsiklovir", ["250mg", "500mg"], ["kapsula"]),
        ("Imiquimod", "Imikvimod", ["5%"], ["krem"]),
        ("Polyoxidonium", "Azoksimer bromid", ["6mg", "12mg"], ["tabletka"]),
        ("Cycloferon", "Meglumin akridonatsetat", ["150mg", "400mg"], ["tabletka"]),
        ("Kagocel", "Kagotsel", ["12mg"], ["tabletka"]),
        ("Arbidol", "Umifenovir", ["100mg", "200mg"], ["kapsula"]),
        ("Tamiflu", "Oseltamivir", ["30mg", "45mg", "75mg"], ["kapsula"]),
        ("Isoprinosine", "Inosin pranobeks", ["500mg"], ["tabletka"]),
        ("Lavomax", "Tiloron", ["60mg", "125mg"], ["tabletka"]),
        ("Amiksin", "Tiloron", ["60mg", "125mg"], ["tabletka"]),
    ],
    "Onkologiya-kimyo": [
        ("Methotrexate", "Metotreksat", ["2.5mg", "5mg", "10mg"], ["tabletka", "in'ektsiya"]),
        ("5-Fluorouracil", "5-Fluorouratsil", ["500mg"], ["in'ektsiya"]),
        ("Cyclophosphamide", "Siklofosfamid", ["500mg"], ["in'ektsiya"]),
        ("Doxorubicin", "Doksorubitsin", ["50mg"], ["in'ektsiya"]),
        ("Cisplatin", "Tsisp latin", ["50mg", "100mg"], ["in'ektsiya"]),
        ("Paclitaxel", "Paklitaksel", ["30mg", "100mg"], ["in'ektsiya"]),
        ("Docetaxel", "Doketaksel", ["20mg", "80mg"], ["in'ektsiya"]),
        ("Etoposide", "Etozid", ["100mg"], ["in'ektsiya"]),
        ("Vincristine", "Vinkristin", ["1mg"], ["in'ektsiya"]),
        ("Tamoxifen", "Tamoksifen", ["10mg", "20mg"], ["tabletka"]),
        ("Anastrozole", "Anastrozol", ["1mg"], ["tabletka"]),
        ("Capecitabine", "Kapetsitabin", ["150mg", "500mg"], ["tabletka"]),
        ("Imatinib", "Imatinib", ["100mg", "400mg"], ["tabletka"]),
        ("Sorafenib", "Sorafenib", ["200mg"], ["tabletka"]),
        ("Pembrolizumab", "Pembrolizumab", ["25mg/ml"], ["in'ektsiya"]),
        ("Nivolumab", "Nivolumab", ["10mg/ml"], ["in'ektsiya"]),
    ],
    "Sport tibbiyoti": [
        ("Creatine", "Kreatin monohidrat", ["5g"], ["paket"]),
        ("BCAA", "Amino kislota", ["tabletka", "paket"]),
        ("Whey Protein", "Vay protein", ["paket"]),
        ("Glutamine", "L-Glutamin", ["5g", "10g"], ["paket"]),
        ("HMB", "Gidroksimetilbutirat", ["500mg"], ["kapsula"]),
        ("Pre-Workout", "Oldindan", ["paket"]),
        ("Collagen Peptides", "Kollagen peptidlar", ["paket"]),
        ("Electrolyte", "Elektrolit", ["paket"]),
        ("Multivitamin Sport", "Sport multivitamin", ["tabletka"]),
        ("Omega-3 Sport", "Omega-3 sport", ["kapsula"]),
        ("ZMA", "Zink/Magniy", ["tabletka"]),
        ("Tribulus", "Tribulus terrestris", ["tabletka"]),
        ("Ashwagandha", "Ashwagandha", ["tabletka"]),
        ("Beta-Alanine", "Beta-alanin", ["tabletka"]),
        ("L-Carnitine", "L-Karnitin", ["tabletka", "sprey"]),
        ("CLA", "Konjuge linol kislota", ["kapsula"]),
    ],
    "Kosmetologiya": [
        ("Retinol cream", "Retinol", ["0.3%", "0.5%", "1%"], ["krem"]),
        ("Vitamin C serum", "Askorbin kislota", ["10%", "15%", "20%"], ["serum"]),
        ("Hyaluronic acid", "Gialuron kislota", ["1%", "2%"], ["serum"]),
        ("Niacinamide", "Nikotinamid", ["5%", "10%"], ["serum"]),
        ("Salicylic acid", "Salitsil kislota", ["0.5%", "2%"], ["krem"]),
        ("Glycolic acid", "Glikol kislota", ["5%", "10%"], ["tonik"]),
        ("Benzoyl peroxide", "Benzoyl peroksid", ["2.5%", "5%"], ["krem"]),
        ("Ceramide cream", "Seramidlar", ["krem"]),
        ("Collagen cream", "Kollagen", ["krem"]),
        ("Peptide serum", "Peptidlar", ["serum"]),
        ("Sunscreen SPF50", "Quyoshdan himoya", ["50+"], ["krem"]),
        ("Micellar water", "Mitsellar suv", ["200ml", "400ml"], ["eritma"]),
        ("Face Wash", "Yuzni yuvish", ["100ml"], ["gel"]),
        ("Toner", "Toner", ["200ml"], ["eritma"]),
        ("Sheet Mask", "Yuz niqobi", ["niqob"]),
        ("Eye Cream", "Ko'z atrofi kremi", ["15ml"], ["krem"]),
        ("Lip Balm", "Lab balzami", ["10g"], ["balzam"]),
        ("Body Lotion", "Tana losioni", ["200ml"], ["losion"]),
        ("Hair Oil", "Soch moyi", ["100ml"], ["moy"]),
        ("Shampoo", "Shampun", ["200ml", "400ml"], ["shampun"]),
    ],
    "Gigiena": [
        ("Colgate", "Fluor", ["75ml", "100ml"], ["toothpaste"]),
        ("Oral-B", "Fluor", ["75ml", "100ml"], ["toothpaste"]),
        ("Listerine", "Antiseptik", ["250ml", "500ml"], ["eritma"]),
        ("Chlorhexidine", "Hlorgeksidin", ["100ml"], ["eritma"]),
        ("Nivea", "Nemlendirici", ["100ml", "200ml"], ["krem"]),
        ("Dove", "Nemlendirici", ["100ml", "250ml"], ["gel"]),
        ("Vaseline", "Vazelin", ["100ml"], ["maz"]),
        ("Deodorant", "Ter to'xtatuvchi", ["50ml", "150ml"], ["sprey"]),
        ("Hand Sanitizer", "Qo'l tozalovchi", ["50ml", "100ml"], ["gel"]),
        ("Wet Wipes", "Nam salfetka", ["30", "60"], ["salfetka"]),
        ("Shower Gel", "Dush geli", ["250ml", "500ml"], ["gel"]),
        ("Intimate Wash", "Maxsus yuvish", ["200ml"], ["eritma"]),
    ],
    "Tibbiy buyumlar": [
        ("Termometr", "Elektron", ["digi"]),
        ("Tensiometr", "Qon bosimi", ["avto"]),
        ("Glukometr", "Qand tahlili", ["digi"]),
        ("Nebulizer", "Inhalatsiya", ["kompressor"]),
        ("Pulse Oximeter", "Kislorod", ["digi"]),
        ("Massager", "Massaj", ["elctrik"]),
        ("Bandage", "Bandaj", ["10sm", "15sm"]),
        ("Gauze", "Marle", ["5m"]),
        ("Syringe", "Shprits", ["2ml", "5ml", "10ml"]),
        ("Gloves", "Qo'lqop", ["S", "M", "L"]),
        ("Mask", "Niqob", ["50", "100"]),
        ("Orthopedic Belt", "Ortopedik kamar", ["M", "L", "XL"]),
        ("Wheelchair", "Nogironlar aravachasi", ["cheklangan"]),
    ],
    "O'simlik preparatlari": [
        ("Valeriana", "Valeriana", ["tabletka", "tomchi"]),
        ("Passiflora", "Passiflora", ["tabletka"]),
        ("St. John's Wort", "Ziravor o'ti", ["tabletka"]),
        ("Ginkgo Biloba", "Ginkgo biloba", ["40mg", "80mg"], ["tabletka"]),
        ("Echinacea", "Echinacea", ["tabletka", "tomchi"]),
        ("Milk Thistle", "O'simlik sut'i", ["140mg"], ["kapsula"]),
        ("Turmeric", "Zanjabil", ["500mg"], ["tabletka"]),
        ("Ginger", "Zanjabil", ["tabletka"]),
        ("Garlic", "Sarimsoq", ["tabletka"]),
        ("Cranberry", "Kranberi", ["tabletka"]),
        ("Aloe Vera", "Aloe vera", ["tabletka", "gel"]),
        ("Chamomile", "Romon chamomile", ["tabletka", "tomchi"]),
        ("Hawthorn", "O'rik o'g'iti", ["tabletka", "tomchi"]),
        ("Rosehip", "It gullari", ["tabletka", "sirop"]),
        ("Propolis", "Proopolis", ["tabletka", "tomchi"]),
        ("Pollen", "Chang", ["paket"]),
    ],
    "Uy sharoitida davolash": [
        ("Paratsetamol", "Paratsetamol", ["500mg"], ["tabletka"]),
        ("Ibuprofen", "Ibuprofen", ["400mg"], ["tabletka"]),
        ("Aspirin", "Acetilsalitsil kislota", ["500mg"], ["tabletka"]),
        ("ORS", "Oral rehidratatsiya", ["paket"]),
        ("Activated Charcoal", "Ko'mir", ["250mg"], ["tabletka"]),
        ("Mezim", "Pancreatin", ["10000"], ["tabletka"]),
        ("Validol", "Validol", ["60mg"], ["tabletka"]),
        ("Corvalol", "Etamil bromizovalerianat", ["25ml"], ["eritma"]),
        ("Furacilin", "Nitrofural", ["0.2%"], ["eritma"]),
        ("Hydrogen Peroxide", "Vodorod peroksid", ["3%"], ["eritma"]),
        ("Iodine", "Yod", ["5%"], ["eritma"]),
        ("Brilliant Green", "Yashil", ["eritma"]),
        ("Calendula", "Calendula", ["tomchi", "maz"]),
        ("Salt", "Tuz", ["paket"]),
        ("Soda", "Soda", ["paket"]),
    ],
    "Ayollar salomatligi": [
        ("Folic Acid", "Folik kislota", ["5mg"], ["tabletka"]),
        ("Iron", "Temir", ["tabletka"]),
        ("Calcium + D3", "Kaltsiy + D3", ["tabletka"]),
        ("Prenatal", "Homiladorlik", ["tabletka"]),
        ("Duphaston", "Dydrogesteron", ["10mg"], ["tabletka"]),
        ("Utrozhestan", "Progesteron", ["100mg", "200mg"], ["kapsula"]),
        ("Clomiphene", "Klomifen", ["50mg"], ["tabletka"]),
        ("Postinor", "Levonorgestrel", ["0.75mg"], ["tabletka"]),
        ("Yarina", "Drospirenon/Ethinylestradiol", ["tabletka"]),
        ("Jeanine", "Dienogest/Ethinylestradiol", ["tabletka"]),
        ("Regulon", "Desogestrel/Ethinylestradiol", ["tabletka"]),
        ("Clotrimazole", "Klotrimazol", ["100mg", "500mg"], ["tabletka"]),
        ("Pimafucin", "Natamitsin", ["100mg"], ["shamcha"]),
        ("Hexicon", "Hlorgeksidin", ["eritma", "shamcha"]),
        ("Lactonorm", "Laktobatsilluslar", ["kapsula"]),
    ],
    "Bolalar salomatligi": [
        ("Paratsetamol bolalar", "Paratsetamol", ["100mg", "120mg"], ["suspenziya"]),
        ("Ibuprofen bolalar", "Ibuprofen", ["100mg/5ml"], ["suspenziya"]),
        ("Cefekon", "Paratsetamol", ["100mg", "250mg"], ["shamcha"]),
        ("Viferon bolalar", "Interferon", ["shamcha"]),
        ("Anaferon bolalar", "Homeopatik", ["tabletka"]),
        ("Lazolvan bolalar", "Ambroksol", ["15mg/5ml"], ["sirop"]),
        ("ACC bolalar", "Atsetilsistein", ["100mg", "200mg"], ["paket"]),
        ("Prospan bolalar", "Efeushya", ["sirop"]),
        ("Smecta bolalar", "Diosmektit", ["3g"], ["paket"]),
        ("Linex bolalar", "Laktobatsilluslar", ["kapsula"]),
        ("Bifiform bolalar", "Bifidobakteriyalar", ["kapsula"]),
        ("Supraks bolalar", "Tsefiksim", ["100mg"], ["suspenziya"]),
        ("Flemoksin bolalar", "Amoksitsillin", ["125mg", "250mg"], ["suspenziya"]),
        ("Zodak bolalar", "Setirizin", ["5mg"], ["tomchi"]),
    ],
    "Keksalik salomatlik": [
        ("Calcium", "Kaltsiy", ["tabletka"]),
        ("Vitamin D", "D3 vitamini", ["tabletka"]),
        ("Magnesium", "Magniy", ["tabletka"]),
        ("CoQ10", "Ubiquinon", ["100mg", "200mg"], ["kapsula"]),
        ("Omega-3", "Omega-3", ["1000mg"], ["kapsula"]),
        ("Glucosamine", "Glükozamin", ["500mg"], ["tabletka"]),
        ("Chondroitin", "Xondroitin", ["500mg"], ["tabletka"]),
        ("Collagen", "Kollagen", ["tabletka", "paket"]),
        ("Vitamin B12", "B12 vitamini", ["1000mcg"], ["tabletka"]),
        ("Ginkgo", "Ginkgo biloba", ["40mg"], ["tabletka"]),
        ("Melatonin", "Melatonin", ["3mg", "5mg"], ["tabletka"]),
        ("Saw Palmetto", "Palma mevasi", ["tabletka"]),
    ],
    "Hayvonlar uchun": [
        ("Antibiotik itlar", "Amoksitsillin", ["250mg", "500mg"], ["tabletka"]),
        ("Dewormer itlar", "Pirantel", ["tabletka"]),
        ("Flea Collar", "Bit", ["yoqa"]),
        ("Tick Spray", "Chayon", ["sprey"]),
        ("Joint Supplement itlar", "Bo'g'im", ["tabletka"]),
        ("Vitamin itlar", "Vitamin", ["tabletka", "sirop"]),
        ("Wound Healing", "Yara", ["maz"]),
        ("Shampoo itlar", "Shampun", ["shampun"]),
        ("Skin Cream itlar", "Teri", ["krem"]),
        ("Calming Supplement", "Tinchlantiruvchi", ["tabletka"]),
    ],
    "Parfyumeriya": [
        ("Eau de Parfum", "Atir", ["50ml", "100ml"], ["atir"]),
        ("Eau de Toilette", "Tualet suvi", ["50ml", "100ml"], ["atir"]),
        ("Body Mist", "Tana spreyi", ["100ml", "200ml"], ["sprey"]),
        ("Perfume Oil", "Atir moyi", ["10ml"], ["moy"]),
        ("Room Fragrance", "Xona atiri", ["100ml"], ["sprey"]),
        ("Solid Perfume", "Qattiq atir", ["10g"], ["atir"]),
    ],
    "Tish og'riq": [
        ("Denta", "Lidokain", ["10%"], ["gel"]),
        ("Kalgel", "Lidokain", ["gel"]),
        ("Dentinoks", "Lidokain", ["gel"]),
        ("Ibuprofen", "Ibuprofen", ["400mg"], ["tabletka"]),
        ("Nurofen Express", "Ibuprofen", ["200mg", "400mg"], ["kapsula"]),
        ("Ketanov", "Ketorolak", ["10mg"], ["tabletka"]),
        ("Nimesil", "Nimesulid", ["100mg"], ["paket"]),
        ("Nimulid", "Nimesulid", ["100mg"], ["tabletka"]),
        ("Aertal", "Aceklofenak", ["100mg"], ["tabletka"]),
    ],
    "Oshqozon": [
        ("De-Nol", "Vismut subtsitrat", ["120mg"], ["tabletka"]),
        ("Ultop", "Omeprazol", ["20mg", "40mg"], ["kapsula"]),
        ("Nexium", "Esomeprazol", ["20mg", "40mg"], ["tabletka"]),
        ("Pariet", "Rabeprazol", ["10mg", "20mg"], ["tabletka"]),
        ("Famotidin", "Famotidin", ["20mg", "40mg"], ["tabletka"]),
        ("Maalox", "Alüminiy/Magniy", ["suspenziya"]),
        ("Almagel", "Alüminiy/Magniy", ["suspenziya"]),
        ("Fosfalugel", "Alüminiy fosfat", ["gel"]),
        ("Smecta", "Diosmektit", ["paket"]),
        ("Enterosgel", "Metilsilatik kislota", ["gel"]),
        ("Polysorb", "Kolloidli silika", ["paket"]),
        ("Lactofiltrum", "Laktuloza/Lignin", ["tabletka"]),
        ("Linex", "Laktobatsilluslar", ["kapsula"]),
        ("Bifiform", "Bifidobakteriyalar", ["kapsula"]),
        ("Motilium", "Domperidon", ["tabletka"]),
        ("Trimedat", "Trimebutin", ["tabletka"]),
        ("Duspatalin", "Mebeverin", ["tabletka"]),
        ("No-Spa", "Drotaverin", ["tabletka"]),
    ],
}

MANUFACTURERS = {
    "Xitoy": ["Shanghai Pharma", "Sinopharm", "Harbin Pharma", "Guangzhou Pharma", "Beijing Pharma", "Sino Biopharm", "Topfond Pharma", "Tasly Pharma"],
    "Rossiya": ["Farmstandart", "R-pharm", "Borisovsky", "Pharmtechnologia", "Valenta", "Synthesis", "Stada CIS", "Ozon"],
    "Hindiston": ["Cipla", "Sun Pharma", "Dr. Reddy's", "Ranbaxy", "Zydus", "Aurobindo", "Lupin", "Glenmark"],
    "Turkiya": ["Abdi Ibrahim", "Sanovel", "Sandoz", "Bilim", "İlko", "Eczacıbaşı", "Deva"],
    "Germaniya": ["Bayer", "Stada", "Berlin-Chemie", "Hexal", "Ratiopharm", "Sandoz", "Merck"],
    "Shvetsariya": ["Novartis", "Roche", "Basilea", "Vifor", "Spirig"],
    "Italiya": ["Angelini", "Zambon", "Chiesi", "IBSA", "Menarini"],
    "Fransiya": ["Sanofi", "Servier", "Boiron", "Pierre Fabre"],
    "AQSH": ["Pfizer", "Merck", "Abbott", "Bristol-Myers", "Eli Lilly", "Amgen", "Gilead"],
    "Buyuk Britaniya": ["GSK", "AstraZeneca", "Boots", "Mylan"],
    "Isroil": ["Teva", "Dexcel", "Rafa"],
    "Yaponiya": ["Takeda", "Daiichi Sankyo", "Astellas"],
    "Janubiy Koreya": ["Samsung", "Celltrion", "Hanmi", "Daewoong", "LG Chem"],
    "O'zbekiston": ["Davr Farm", "Samarqand Farm", "Toshkent Farm", "Farmkon"],
}
COUNTRIES = list(MANUFACTURERS.keys())

PHARMACY_NAMES = [
    "Farmalife Dorixona", "Sog'lik Dorixona", "Dorixona 777",
    "Aziza Dorixona", "Davolux Dorixona", "Hayot Dorixona",
    "Shifokor Dorixona", "Salomatlik Dorixona", "Farm-Dorixona",
    "O'zbekiston Dorixona", "Milliy Dorixona", "Eco Dorixona",
]

BRAND_PREFIXES = ["Neo", "Bio", "Vita", "Pro", "Maxi", "Super", "Ultra", "Metro", "Penta", "Alpha", "Omega", "Sigma", "Sano", "Vero", "Farma", "Medica", "Sanita", "Natura", "Salus", "Aqua"]
BRAND_SUFFIXES = ["zol", "max", "fort", "pro", "plus", "vit", "din", "sin", "tol", "sol", "mix", "pax", "dex", "nex", "lex", "cal", "gel", "rin", "set", "fen", "pin", "min", "lin", "nol", "zid", "cin"]

def gen_image_path(form):
    form_images = {
        "tabletka": "/images/medicines/paracetamol.jpg",
        "kapsula": "/images/medicines/capsule.jpg",
        "sirop": "/images/medicines/syrup.jpg",
        "suspenziya": "/images/medicines/syrup.jpg",
        "gel": "/images/medicines/gel.jpg",
        "maz": "/images/medicines/gel.jpg",
        "krem": "/images/medicines/gel.jpg",
        "sprey": "/images/medicines/spray.jpg",
        "damla": "/images/medicines/spray.jpg",
        "in'ektsiya": "/images/medicines/injection.jpg",
        "inhalyatsiya": "/images/medicines/inhaler.jpg",
        "inhalyator": "/images/medicines/inhaler.jpg",
        "shamcha": "/images/medicines/suppository.jpg",
        "pastilka": "/images/medicines/capsule.jpg",
        "eritma": "/images/medicines/spray.jpg",
        "paket": "/images/medicines/syrup.jpg",
        "pasta": "/images/medicines/gel.jpg",
        "tomchi": "/images/medicines/spray.jpg",
        "shampun": "/images/medicines/gel.jpg",
        "toothpaste": "/images/medicines/gel.jpg",
        "jel": "/images/medicines/gel.jpg",
        "serum": "/images/medicines/spray.jpg",
        "tonik": "/images/medicines/spray.jpg",
        "losion": "/images/medicines/syrup.jpg",
        "atir": "/images/medicines/spray.jpg",
        "yoqa": "/images/medicines/capsule.jpg",
        "niqob": "/images/medicines/gel.jpg",
        "balzam": "/images/medicines/gel.jpg",
        "konditsioner": "/images/medicines/gel.jpg",
        "foam": "/images/medicines/syrup.jpg",
        "digi": "/images/medicines/capsule.jpg",
        "kompressor": "/images/medicines/inhaler.jpg",
        "avto": "/images/medicines/capsule.jpg",
        "elctrik": "/images/medicines/capsule.jpg",
        "cheklangan": "/images/medicines/capsule.jpg",
        "dastgoh": "/images/medicines/inhaler.jpg",
        "salfetka": "/images/medicines/capsule.jpg",
    }
    return form_images.get(form, "/images/medicines/paracetamol.jpg")

def gen_price():
    return random.choice([
        random.randint(500, 5000), random.randint(5000, 15000),
        random.randint(15000, 35000), random.randint(35000, 80000),
        random.randint(80000, 200000),
    ])

if __name__ == "__main__":
    medicines = []
    prices = {}
    idx = 1

    for category, drugs in ALL_CATEGORIES.items():
        for drug_tuple in drugs:
            if len(drug_tuple) == 4:
                drug_name, generic, dosages, forms = drug_tuple
            else:
                drug_name, generic, dosages = drug_tuple
                forms = ["tabletka"]
            for dosage in dosages:
                form = random.choice(forms)
                country = random.choice(COUNTRIES)
                manufacturer = random.choice(MANUFACTURERS[country])
                name = f"{drug_name} {dosage}"
                price = gen_price()
                med = {
                    "id": f"med-{idx}", "name": name,
                    "slug": name.lower().replace(" ", "-").replace("'", "")[:60],
                    "description": f"{name} — {generic} asosidagi sifatli dori vositasi. {category} kategoriyasiga kiradi.",
                    "category": category, "form": form, "dosage": dosage,
                    "unitPrice": price, "oldPrice": price * 1.2,
                    "isAvailable": random.random() > 0.1,
                    "rating": round(random.uniform(3.5, 5.0), 1),
                    "reviewCount": random.randint(5, 800),
                    "image": gen_image_path(form), "manufacturer": manufacturer, "country": country,
                    "prescriptionRequired": random.random() < 0.3,
                    "isPopular": random.random() < 0.08,
                    "isFeatured": random.random() < 0.04,
                    "discount": random.randint(0, 25) if random.random() < 0.3 else 0,
                    "unit": "tabletka" if form in ["tabletka", "kapsula"] else form,
                    "packSize": random.choice([1, 2, 3, 5, 10, 20, 30, 60]),
                    "minimumOrder": 1,
                }
                medicines.append(med)
                pl = []
                for _ in range(random.randint(3, 8)):
                    pl.append({
                        "pharmacyId": f"ph-{random.randint(1, 152)}",
                        "pharmacyName": random.choice(PHARMACY_NAMES),
                        "pharmacyLogo": f"/images/pharmacy-{random.randint(1, 12)}.svg",
                        "pharmacyRating": round(random.uniform(4.0, 5.0), 1),
                        "price": price + random.randint(-int(price * 0.15), int(price * 0.2)),
                        "originalPrice": price + random.randint(0, int(price * 0.3)),
                        "discount": random.randint(0, 25),
                        "deliveryFee": random.choice([0, 5000, 10000]),
                        "deliveryTime": random.choice(["20 daqiqa", "30 daqiqa", "1 soat", "2 soat"]),
                        "isAvailable": random.random() > 0.15,
                        "stockQuantity": random.randint(0, 200),
                        "distance": round(random.uniform(0.5, 15.0), 1),
                    })
                prices[f"med-{idx}"] = pl
                idx += 1

    # Fill to 30k
    while len(medicines) < 30000:
        cat = random.choice(list(ALL_CATEGORIES.keys()))
        base = f"{random.choice(BRAND_PREFIXES)}{random.choice(BRAND_SUFFIXES)}"
        dosage = random.choice(["50mg", "100mg", "200mg", "250mg", "500mg", "1g", "5ml", "10ml"])
        form = random.choice(["tabletka", "kapsula", "sirop", "gel", "sprey", "in'ektsiya", "maz", "krem", "damla"])
        country = random.choice(COUNTRIES)
        manufacturer = random.choice(MANUFACTURERS[country])
        name = f"{base} {dosage}"
        price = gen_price()
        med = {
            "id": f"med-{idx}", "name": name,
            "slug": name.lower().replace(" ", "-").replace("'", "")[:60],
            "description": f"{name} — {cat} kategoriyasiga kiruvchi sifatli dori vositasi.",
            "category": cat, "form": form, "dosage": dosage,
            "unitPrice": price, "oldPrice": price * 1.2,
            "isAvailable": random.random() > 0.1,
            "rating": round(random.uniform(3.5, 5.0), 1),
            "reviewCount": random.randint(5, 800),
            "image": gen_image_path(form), "manufacturer": manufacturer, "country": country,
            "prescriptionRequired": random.random() < 0.25,
            "isPopular": random.random() < 0.08,
            "isFeatured": random.random() < 0.04,
            "discount": random.randint(0, 25) if random.random() < 0.3 else 0,
            "unit": "tabletka" if form in ["tabletka", "kapsula"] else form,
            "packSize": random.choice([1, 2, 3, 5, 10, 20, 30, 60]),
            "minimumOrder": 1,
        }
        medicines.append(med)
        pl = []
        for _ in range(random.randint(3, 8)):
            pl.append({
                "pharmacyId": f"ph-{random.randint(1, 152)}",
                "pharmacyName": random.choice(PHARMACY_NAMES),
                "pharmacyLogo": f"/images/pharmacy-{random.randint(1, 12)}.svg",
                "pharmacyRating": round(random.uniform(4.0, 5.0), 1),
                "price": price + random.randint(-int(price * 0.15), int(price * 0.2)),
                "originalPrice": price + random.randint(0, int(price * 0.3)),
                "discount": random.randint(0, 25),
                "deliveryFee": random.choice([0, 5000, 10000]),
                "deliveryTime": random.choice(["20 daqiqa", "30 daqiqa", "1 soat", "2 soat"]),
                "isAvailable": random.random() > 0.15,
                "stockQuantity": random.randint(0, 200),
                "distance": round(random.uniform(0.5, 15.0), 1),
            })
        prices[f"med-{idx}"] = pl
        idx += 1

    with open('src/lib/generated-data.json') as f:
        data = json.load(f)
    data['generatedMedicines'] = medicines
    data['generatedMedicinePrices'] = prices
    with open('src/lib/generated-data.json', 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    cats = {}
    for m in medicines:
        cats[m['category']] = cats.get(m['category'], 0) + 1
    print(f"Total medicines: {len(medicines)}")
    print(f"Categories: {len(cats)}")
    for c in sorted(cats.keys()):
        print(f"  {c}: {cats[c]}")
